/* ============================================================
   dummies-extra4.js — "For Dummies" intros for VCO/NCO/CFO/DLL/
   turbo/LDPC. Extends CONTENT_DUMMIES (defined in content.js).
   ============================================================ */
Object.assign(CONTENT_DUMMIES, {
  'vco': String.raw`<p>A VCO is an oscillator with a <b>tuning knob you turn with a voltage</b> instead of your fingers. Feed it a higher control voltage and it hums at a higher frequency; lower the voltage and the pitch drops — like a <b>slide whistle</b> whose note you set electrically.</p><p>That "voltage in, frequency out" behaviour is incredibly useful: it's the adjustable oscillator a feedback loop can steer. Put a VCO inside a Phase-Locked Loop and the loop nudges its control voltage until the VCO's tone lines up perfectly with a reference — that's how radios generate precise tuning frequencies.</p><p>The catch is that the same sensitivity that lets you tune it also lets <b>noise</b> on the control line wobble the frequency, so a "twitchy" (high-gain) VCO is easy to tune but noisier. Balancing tuning range against noise is the heart of oscillator design, and VCOs sit at the core of nearly every transmitter and receiver.</p>`,
  'nco': String.raw`<p>An NCO is the <b>all-digital version of a VCO</b> — it makes a tone out of pure arithmetic, no analog oscillator at all. Picture a car's odometer that rolls over and over: each clock tick you add a fixed number to a running counter (the "phase"), and when it wraps around, that's one cycle of your wave.</p><p>The clever bit is a lookup table that turns each counter value into the matching point on a sine wave — so out comes a smooth tone. Because the frequency is set by the <b>number you add</b> each tick (f_out = number × clock ÷ 2^N), it's perfectly repeatable and you can change it instantly with pinpoint precision.</p><p>This "direct digital synthesis" is everywhere inside modern radios and SDRs: it generates the tuning tones, shifts signals up and down in frequency, and recovers carriers digitally — doing the VCO's job with a counter and a table.</p>`,
  'cfo': String.raw`<p>Carrier Frequency Offset is what happens when the transmitter and receiver <b>aren't tuned to exactly the same frequency</b> — their internal "tuning forks" differ by a tiny amount (or the two are moving, adding Doppler shift). Even a minuscule mismatch causes trouble.</p><p>The effect is that the received picture <b>slowly spins</b>: on a constellation display the points rotate round and round, like watching a clock's second hand, because the small frequency error piles up into an ever-growing phase twist. Left alone, the spinning smears the symbols together and the link fails.</p><p>So a receiver must <b>measure and undo</b> the offset (using pilots or a frequency-locked loop, then "de-rotating" the signal). CFO is especially deadly for OFDM (Wi-Fi, LTE, 5G), where it makes the closely-packed subcarriers bleed into each other — which is why so much sync effort goes into killing it.</p>`,
  'dll': String.raw`<p>A Delay-Locked Loop lines up one clock with another by <b>slowing it down just the right amount</b> — it feeds the clock through an adjustable delay and tunes that delay until the edges land exactly on top of the reference, like nudging a marcher until they step perfectly in time with the band.</p><p>The big difference from a PLL is that a DLL uses a <b>delay line, not an oscillator</b>. It doesn't generate a new frequency, it just shifts an existing clock's timing. Because a delay is a simple, direct action (no "winding up"), a DLL is inherently stable and, crucially, it <b>doesn't accumulate jitter</b> the way a free-running oscillator does.</p><p>That makes DLLs the go-to for precise timing alignment inside chips — de-skewing clocks, generating several evenly-spaced clock phases, and hitting the tight timing of DDR memory and high-speed FPGA/SoC interfaces. (The "early-late" DLL that tracks GPS code timing is a cousin covered separately.)</p>`,
  'turbo-codes': String.raw`<p>Turbo codes are an error-correcting scheme so good it stunned engineers when it appeared in 1993 — it gets you <b>astonishingly close to the theoretical speed limit</b> (Shannon's bound) that everyone had assumed was practically unreachable.</p><p>The trick has two parts. First, the encoder describes your data <b>two different ways</b> — once normally, and once after shuffling the bits into a scrambled order — so the two "views" fail in different situations. Then two decoders <b>take turns and argue</b>: each makes a soft guess about each bit, hands its confidence to the other, which refines it and hands it back, round after round, until they converge on an answer. That back-and-forth "turbo" feedback is where the name comes from.</p><p>This near-miraculous performance is why turbo codes powered 3G and 4G phones, deep-space probes, and satellite links — squeezing every last decibel out of a weak signal.</p>`,
  'ldpc': String.raw`<p>LDPC is another code that snuggles right up to the theoretical limit — and it works a bit like a giant game of <b>Sudoku for parity checks</b>. Every bit of your message has to satisfy several simple "these bits must add up right" rules, and the rules overlap so each bit is checked from many angles.</p><p>To decode, you don't solve it all at once — you <b>pass hints around a web</b>. Each check tells the bits it touches "based on my rule, here's what I think you should be," each bit gathers all the opinions about it, updates its best guess, and the whispers keep flowing back and forth until every check is finally satisfied and the message is consistent. This "belief propagation" over a sparse network is what makes it both powerful and practical.</p><p>Invented in 1962 but too demanding for the computers of the day, LDPC was rediscovered in the 1990s and now runs in Wi-Fi, 5G data channels, satellite TV (DVB-S2), and hard-drive/flash storage — often edging out turbo codes.</p>`
});
