/* ============================================================
   dummies-extra2.js — "For Dummies" intros for the newest topics.
   Extends CONTENT_DUMMIES (defined in content.js).
   ============================================================ */
Object.assign(CONTENT_DUMMIES, {
  'am': String.raw`<p>Amplitude Modulation is the oldest radio trick: take a steady high-frequency "carrier" wave and make it <b>louder and softer</b> in step with your message — like speaking into a fan and letting your voice ride on the breeze. Where your voice is loud, the wave gets tall; where it's quiet, the wave shrinks.</p><p>The receiver just traces the <b>outline (the envelope)</b> of that wobbling wave to recover your original sound — which is why an AM radio can be dead simple and cheap. Push it too hard, though (over-modulation), and the outline gets mangled and the sound distorts.</p><p>AM is how old-school AM broadcast radio, aircraft voice radios, and CB radios work. It's simple and long-range, but wasteful of power and easily scratched up by electrical noise (that crackle you hear in a thunderstorm) — which is exactly the weakness FM was invented to fix.</p>`,
  'fm': String.raw`<p>Frequency Modulation sends your message by nudging the carrier's <b>pitch</b> up and down instead of its loudness — higher frequency when the message rises, lower when it falls. Think of it like <b>humming a tune</b>: the volume stays constant, but the note glides around to carry the melody.</p><p>Because the information lives in the pitch (frequency), not the loudness, FM barely cares about the crackle and static that plague AM — noise mostly messes with amplitude, which FM ignores. That's why FM radio sounds so clean, and why the loudest station tends to completely take over a frequency (the "capture effect").</p><p>The price is that FM spreads across <b>more bandwidth</b> — it trades airspace for that crisp, noise-resistant sound. FM broadcast radio, walkie-talkies, and the audio of old analog TV all use it.</p>`,
  'qpsk': String.raw`<p>QPSK is BPSK's more efficient sibling. Instead of flipping the wave between just two positions (for a 0 or a 1), it uses <b>four distinct phases</b> — like a compass pointing NE, NW, SE, or SW — and each direction stands for <b>two bits at once</b>.</p><p>The clever part: those four points are really just <b>two independent BPSK signals stacked together</b>, one riding a cosine (the "I" channel) and one a sine (the "Q" channel), which don't interfere because they're 90° apart. So you send twice the data in the same space.</p><p>And here's the near-magical bit: doing this costs you nothing in reliability — the error rate per bit is the same as plain BPSK. That "twice the data, same robustness" is why QPSK (and its cousins) is everywhere: Wi-Fi, LTE, satellite, cable.</p>`,
  'rrc-filter': String.raw`<p>When you send symbols back-to-back, sharp on/off pulses smear into each other and hog bandwidth. A Root-Raised-Cosine filter <b>rounds off the pulse shapes</b> so neighbours don't blur together — but with a twist: the job is deliberately <b>split into two halves</b>.</p><p>Half the shaping is done at the transmitter and half at the receiver, like <b>two puzzle pieces that only form the perfect shape when joined</b>. On its own, one RRC filter doesn't fully prevent smearing; but transmitter-RRC followed by receiver-RRC multiply together into a "raised cosine" that's perfectly smear-free at the sampling instants.</p><p>Splitting it this way has a bonus: the receiver's half also acts as the optimal "matched filter" that pulls the signal cleanest out of noise. That's why virtually every modern modem — LTE, Wi-Fi, satellite — uses matched RRC filters at both ends.</p>`,
  'bandwidth': String.raw`<p>Bandwidth is simply <b>how much room on the frequency dial a signal takes up</b> — like the width of a doorway, or the number of lanes on a highway. A pure whistle needs almost none; rich music or fast data needs a lot.</p><p>There's a fundamental link: <b>the faster you want to send data, the more bandwidth you need</b>. Cramming more bits per second is like pushing more cars through — eventually you need more lanes. That's why a phone call needs a sliver of spectrum but streaming 4K video needs a big chunk.</p><p>Engineers actually measure "width" a few different ways (where the signal drops to half power, where it first hits zero, or where 99% of its energy sits), but they're all getting at the same idea. Bandwidth is one of the two great resources in all of radio — the other being power — and spectrum regulators sell it for billions.</p>`,
  'early-late-correlator': String.raw`<p>To read a signal correctly, a receiver has to sample it at exactly the right instants — too early or too late and it grabs mush. The Early-Late correlator is a clever way to <b>stay perfectly on time</b>, like a fielder constantly adjusting so the ball lands right in the glove.</p><p>It takes <b>three peeks</b>: one a little early, one right on time (prompt), and one a little late. If it's sampling too soon, the "early" peek looks stronger than the "late" one; too late, and the reverse. The receiver just <b>nudges its timing toward whichever side is weaker</b> until early and late are perfectly balanced — dead-on.</p><p>This little feedback trick (a "delay-locked loop") is exactly how a GPS receiver locks onto a satellite's code to the billionth of a second, and how modems recover symbol timing. It's the timing twin of the PLL, which locks phase instead.</p>`,
  'polarization': String.raw`<p>A radio wave wiggles its electric field in some direction as it travels — and polarization is simply <b>which way that wiggle points</b>. It can wave straight up-and-down (vertical), side-to-side (horizontal), or spiral around like a corkscrew (circular).</p><p>It matters because a receiving antenna is <b>picky about orientation</b> — like <b>polarized sunglasses</b> that block glare, or a letter that only slides through a mail slot the right way up. If the transmitter is sending "vertical" and your antenna is "horizontal," you can lose almost all the signal, even if it's strong.</p><p>That's why your car radio antenna is tilted a certain way, why satellite dishes fuss over polarization to fit twice as many channels in the same band, and why GPS and satellite links use <b>circular</b> polarization — a spiral doesn't care how your handset is rotated, so it keeps working whichever way you hold it.</p>`
});
