/* ============================================================
   dummies-extra3.js — "For Dummies" intros for the protocol topics.
   Extends CONTENT_DUMMIES (defined in content.js).
   ============================================================ */
Object.assign(CONTENT_DUMMIES, {
  'rs232': String.raw`<p>RS-232 is the granddaddy of "serial ports" — the way two devices swap data one bit at a time over a couple of wires, like <b>passing notes back and forth through a single slot</b>. It's how old PCs talked to modems, mice, and instruments.</p><p>Because there's no shared clock wire, each byte is wrapped with a <b>"here it comes" start bit and a "that's it" stop bit</b>, so the listener knows where each character begins and ends — like putting a capital letter at the start of a sentence and a full stop at the end. Both sides just have to agree on the speed (the "baud rate") beforehand.</p><p>It's dead simple and everywhere in legacy gear, but it has real limits: it's <b>one-to-one only</b> (no sharing), the voltages are big and single-ended so noise gets in easily, and it fizzles out after ten or fifteen metres. Those weaknesses are exactly what RS-422/485 were built to fix.</p>`,
  'rs422': String.raw`<p>RS-422 keeps RS-232's idea of sending bytes one bit at a time, but fixes its biggest weakness with a clever trick: instead of measuring one wire against ground, it sends each bit as the <b>difference between two wires</b> twisted together.</p><p>Why does that help? Any noise the cable picks up hits <b>both</b> wires almost equally — so when the receiver looks only at the <i>gap</i> between them, the noise <b>cancels out</b>, like two people shouting the same interruption at you and you just listen to the difference in their voices. That lets RS-422 run far faster and much farther — up to about 1200 metres, or 10 megabits per second over short runs.</p><p>It's point-to-point (or one talker to a handful of listeners), and it's the workhorse behind long industrial and instrumentation links where RS-232 would drown in noise.</p>`,
  'rs485': String.raw`<p>RS-485 takes RS-422's noise-beating differential trick and adds a <b>party line</b>: instead of just two devices, <b>up to 32 (or more) devices share one pair of wires</b>, like a group of people on an old telephone party line.</p><p>The catch with a shared line is that only <b>one device may talk at a time</b> — if two drive the wire at once they clash. So there's a "who's turn is it" rule (usually one master polls each device, or each device waits for its cue), and drivers switch off (go "tri-state") when they're done so someone else can speak. The wire is capped at both ends with 120-ohm terminators so signals don't echo back.</p><p>This makes RS-485 the backbone of industrial networks — factory sensors, building automation, Modbus, even DMX stage lighting — anywhere lots of devices need to chat reliably over long, noisy cable runs.</p>`,
  'lvds': String.raw`<p>LVDS is differential signalling (like RS-422) turned into a <b>tiny, ultra-fast whisper</b>. Instead of big voltage swings, it nudges the two wires apart by only about a third of a volt — a small, low-power signal that can still be read cleanly because, again, the noise on both wires cancels.</p><p>Going small and low-power lets it go <b>blazingly fast</b>: LVDS pushes hundreds of megabits to gigabits per second. The trade is distance — it's meant for short hops, like <b>the ribbon cable carrying video from a laptop's guts to its screen</b>, or from a camera sensor to its processor.</p><p>You'll find LVDS wherever a lot of data has to move quickly over a short, controlled path: display panels (FPD-Link), camera links, and high-speed chip-to-chip connections on circuit boards.</p>`,
  'spi': String.raw`<p>SPI is a simple, fast way for a "boss" chip (the master) to talk to helper chips like sensors, memories, and displays. Its trick is a <b>shared clock</b>: the master ticks out a steady beat, and on every tick <b>everyone shifts one bit</b>, in perfect lockstep — like a conductor's baton keeping a small band exactly in time.</p><p>Because there's a clock line, data flies out on one wire (MOSI) while data comes back on another (MISO) <b>at the same time</b> (full-duplex), with no need for start/stop bits or agreed-upon speeds. To pick which helper to talk to, the master pulls that chip's dedicated <b>"you, listen now" (chip-select) line</b> low.</p><p>SPI is wonderfully quick and simple, but it's <b>short-range (same board)</b> and needs a separate select wire per device, with no built-in addressing or error-checking. It's inside almost every gadget, linking microcontrollers to their sensors and flash chips.</p>`,
  'axi': String.raw`<p>AXI is the <b>internal highway system inside a chip</b> — the standard roads that let the processor, memory, and peripherals inside a modern SoC or FPGA move data between each other at high speed.</p><p>Its key idea is a polite <b>"only go when both sides are ready" handshake</b>: the sender raises a "I have data" flag (VALID) and the receiver raises a "I can take it" flag (READY), and a chunk of data moves <b>only when both flags are up</b> — exactly like a metered on-ramp where cars merge only when there's room. If the receiver gets busy, it just lowers READY and the traffic politely waits, nothing is lost.</p><p>AXI also splits traffic into separate lanes for addresses, data, and responses, and supports "bursts" (send an address once, then stream many data beats). That's why it's the backbone that ties together the blocks inside Xilinx/AMD and ARM-based chips — the same silicon families behind RFSoC.</p>`,
  'mil-std-1553': String.raw`<p>MIL-STD-1553 is the <b>ultra-dependable nervous system of military aircraft</b> (and spacecraft) — a data bus designed so that flight-critical boxes can talk without ever getting confused, even amid heavy electrical noise and battle damage.</p><p>It runs like a <b>strict orchestra with one conductor</b>: a single "Bus Controller" tells each device (a "Remote Terminal") exactly when to talk and when to listen — nobody speaks out of turn, so timing is perfectly predictable (deterministic). The data is Manchester-encoded, meaning <b>the clock is baked into every bit</b> (no separate clock wire), and it's sent over a transformer-coupled twisted pair for toughness.</p><p>For safety it's usually <b>doubled up (dual-redundant)</b> — two complete buses, so if one is cut or fails, the other instantly carries on. It's decades old and slow by modern standards (1 Mbit/s), but its rock-solid predictability is why it still flies on countless aircraft, missiles, and satellites.</p>`
});
