/* ============================================================
   dummies.js — plain-English "For Dummies" explanation per topic.
   Populates CONTENT_DUMMIES (defined in content.js). Rendered at
   the top of each topic's Learn tab. No jargon, everyday analogies.
   ============================================================ */
Object.assign(CONTENT_DUMMIES, {
  'comm-basics': String.raw`<p>Sending a message by radio is like <b>mailing a letter</b>: you pack your information up, send it down a noisy road (the "channel"), and unpack it at the other end. Because a bare message can't travel far on its own, we ride it on a fast, strong wave — the <b>carrier</b> — the way a surfer rides a wave to shore. The whole game is getting the message across cleanly using as little power and space as possible.</p>`,
  'noise': String.raw`<p>Noise is the <b>constant background hiss</b> that's always there, like the murmur of a crowded café even when no one's talking to you. It comes from tiny electrons jiggling around because everything warm has energy. The rule is simple: if your voice (the signal) isn't louder than the café chatter (the noise), the other person can't understand you.</p>`,
  'psd': String.raw`<p>Think of the <b>graphic equalizer</b> bars on a music player that show which pitches are loud. Power Spectral Density is exactly that for any signal — a picture of "how much energy sits at each frequency." It lets us see a signal and the noise side by side and ask, "is my signal sticking up above the hiss?"</p>`,
  'noise-floor': String.raw`<p>The noise floor is the <b>quietest whisper your receiver can possibly hear</b>. Anything softer than the ever-present background hiss simply vanishes into it — like trying to hear a pin drop at a rock concert. Everything a radio can detect has to be louder than this floor.</p>`,
  'noise-figure': String.raw`<p>Every amplifier adds a little of its own hiss on top of the unavoidable background — a "noisy" one is like a <b>cheap microphone that buzzes</b>. The surprising part: the <b>very first</b> amplifier matters most, just like the first person in a game of Telephone. Get it wrong there and no amount of cleaning up later can fix it.</p>`,
  'phase-noise': String.raw`<p>A radio has an internal "tuning fork" that's supposed to vibrate at a perfectly steady rate. Phase noise is when that fork <b>jitters slightly</b> instead of keeping perfect time — like a clock whose ticks wobble. That wobble smears the signal and makes precise decoding harder, especially for fancy high-speed formats.</p>`,
  'bpsk': String.raw`<p>The simplest way to send 1s and 0s: flip the wave <b>one way for a "1" and the opposite way for a "0"</b> — like a light switch, up or down. It's super reliable because "up" and "down" are about as easy to tell apart as things get, so it survives even a very noisy, weak connection.</p>`,
  'dbpsk': String.raw`<p>Instead of "up means 1," this version says <b>"did it change? then 1; stayed the same? then 0."</b> You only watch whether the signal flipped compared to a moment ago, so you never need to know which way is "up." That's handy when the receiver is a bit confused about orientation — it just watches for movement.</p>`,
  'matched-filter': String.raw`<p>The receiver already <b>knows the exact shape</b> of the blip it's waiting for, so it hunts for that shape in the noise — like <b>recognizing a friend's voice</b> in a loud room because you know how they sound. It's the mathematically best possible way to fish a known signal out of the hiss.</p>`,
  'evm': String.raw`<p>Imagine throwing <b>darts at a bullseye</b>. EVM is a single score for how scattered your throws are from the center. In radio, the "bullseye" is where each symbol should land, and EVM measures how far the real ones miss. Small scatter = clean signal; big scatter = something's wrong.</p>`,
  'pll': String.raw`<p>A Phase-Locked Loop makes a local oscillator <b>lock onto and follow a rhythm</b>, like <b>tapping your foot in time with a song</b> until you're perfectly in sync. Once locked, it can copy that beat exactly or multiply it — which is how radios generate their precise tuning frequencies.</p>`,
  'fll': String.raw`<p>Like a PLL, but it only cares about <b>matching the speed, not the exact step</b>. If a signal is way off, the more forgiving FLL can catch it first — like <b>roughly matching a runner's pace</b> before you sync your exact stride. Radios often use the FLL to grab a signal, then switch to a PLL for the fine-tuning.</p>`,
  'costas-loop': String.raw`<p>Some radio signals (like BPSK) <b>hide their beat</b> because the data keeps flipping the wave, so a normal PLL has nothing to grab. A Costas loop is a clever trick that <b>figures out the timing anyway</b> — like keeping the rhythm of a song even when the melody keeps inverting.</p>`,
  'dsss': String.raw`<p>Take your signal and <b>smear it thin across a huge band</b> using a secret fast code, so it looks like faint noise to everyone else. Only someone with the same code can un-smear it and hear you — like <b>whispering in a spread-out code</b> only your friend knows. This is literally how GPS is heard even though it arrives weaker than the noise.</p>`,
  'frequency-hopping': String.raw`<p>Keep <b>jumping between channels</b> in a secret pattern, hundreds of times a second. A jammer or eavesdropper can't keep up because you're never in one place long — like a <b>conversation that keeps switching rooms</b>. Even if someone blocks one channel, you only lose the split-second you spent there.</p>`,
  'pn-codes': String.raw`<p>These are <b>"fake random" sequences</b> — they look like random noise but are actually repeatable and known to both sides, like a <b>deck of cards you can shuffle the exact same way twice</b>. Their magic trick: a code only "matches" itself when lined up perfectly, which makes them brilliant for measuring precise timing.</p>`,
  'gold-code': String.raw`<p>A big <b>family of those fake-random codes</b>, specially designed so they <b>barely interfere with each other</b>. That's exactly what you need when lots of users share one frequency — every GPS satellite gets its own code and they don't drown each other out, like everyone at a party wearing a different-colored badge.</p>`,
  'fec': String.raw`<p>Add clever <b>extra bits</b> so the receiver can <b>fix mistakes by itself</b>, without asking you to resend. It's like writing "<b>meet at 3pm (three o'clock)</b>" — if part gets smudged, the built-in backup still makes it clear. You give up a little speed to gain a lot of reliability.</p>`,
  'viterbi': String.raw`<p>A smart guesser that takes a <b>garbled message and works out the most likely original</b> — cleverly, instead of trying every possibility one by one. Think of <b>solving a maze by only ever keeping the best route to each spot</b>. It's the decoder that undoes the error-correction coding.</p>`,
  'sdr': String.raw`<p>A radio where <b>all the tuning and decoding is done in software</b> instead of fixed knobs and circuits. Load different code and the same box becomes an FM radio, a Wi-Fi receiver, a GPS — whatever you want. It's like a <b>smartphone replacing a whole drawer of gadgets</b>.</p>`,
  'adc': String.raw`<p>Turns a smooth real-world signal (like a voice) into <b>numbers a computer understands</b>, by measuring it very quickly and rounding each measurement. It's like <b>tracing a curve with dots on graph paper</b> — the more dots and the finer the grid, the more faithful the copy.</p>`,
  'dac': String.raw`<p>The reverse of an ADC: it turns <b>numbers back into a smooth signal</b> you can hear or transmit. Like <b>connect-the-dots that recreates the original picture</b>, with a filter smoothing out the little steps so it comes out clean.</p>`,
  'ad9361': String.raw`<p>A single chip that packs a <b>whole software-radio front-end</b> into one part — it can tune almost any frequency and hand the signal straight to a computer. It's the popular little <b>engine inside many hobby and professional SDRs</b> (like the pocket-sized PlutoSDR).</p>`,
  'rfsoc': String.raw`<p>A powerhouse chip that <b>samples radio directly at blazing speed</b> and has a computer built right in, so it can juggle <b>many antennas at once</b>. It's the kind of brain behind <b>5G cell towers and modern radar</b> — lots of radio channels handled all in one place.</p>`,
  'rssi': String.raw`<p>This is your phone's <b>"signal bars"</b> — a number for how strong the received signal is. But careful: strong isn't always clear. A powerful signal buried in interference is still hard to understand, the same way a <b>loud voice in a loud room</b> can still be unintelligible.</p>`,
  'path-loss': String.raw`<p>Signals get <b>weaker the farther they travel</b>, like a shout fading into the distance. Go twice as far and it's only a quarter as strong. Higher-pitched (higher-frequency) signals fade even faster — which is why long-range radios prefer lower frequencies.</p>`,
  'link-budget': String.raw`<p>An <b>accountant's tally</b> for a radio link: start with your transmit power, add the antenna boosts, subtract every loss along the way, and see if enough signal is left at the end to be heard. If the final number is in the black, the link works — it's basically a "<b>will this reach?</b>" spreadsheet.</p>`,
  'antenna': String.raw`<p>An antenna <b>turns electricity into radio waves and back again</b> — think of it as a <b>loudspeaker and microphone, but for radio</b>. Its size follows the wavelength, which is why a phone's antenna is tiny while an AM radio tower is enormous.</p>`,
  'antenna-gain': String.raw`<p>Gain is how much an antenna <b>focuses its energy in one direction</b> instead of spraying it everywhere — like a <b>flashlight versus a bare bulb</b>. Same power, but by aiming it the flashlight reaches much farther. Important: it doesn't create extra power, it just concentrates what's there.</p>`,
  'antenna-beamwidth': String.raw`<p>Beamwidth is <b>how wide or narrow that focused beam is</b>. A narrow beam reaches far but you must aim carefully, like a <b>laser pointer</b>; a wide beam covers more area but is weaker, like a <b>lantern</b>. Narrower = more range but trickier to point.</p>`,
  'antenna-types': String.raw`<p>Different antenna shapes for different jobs: a simple <b>rod</b> for all-around coverage, a <b>"fishbone" Yagi</b> (old rooftop TV antenna) for pointing at a distant tower, a <b>dish</b> for long-distance links, a flat <b>patch</b> tucked inside your phone. You pick based on how far, which direction, and how small it needs to be.</p>`,
  'maxwell': String.raw`<p>Four famous rules that, together, explain <b>all of electricity, magnetism, and light</b>. The big "aha": a changing electric field creates a magnetic field, which creates an electric field, and so on — they <b>leapfrog through space as a wave</b>. That wave <i>is</i> radio, microwaves, and visible light — all the same stuff, just different pitches.</p>`
});
