// RF Link & Metrics: RSSI, Path Loss, Link Budget — deep exam-mastery content
CONTENT.topics.push(
  {
    id: 'rssi',
    title: 'RSSI',
    category: 'RF Link & Metrics',
    tags: ['rssi', 'received power', 'dBm', 'snr', 'rsrp', 'rsrq', 'sinr', 'metrics'],
    summary: String.raw`RSSI is the total received power in a channel (signal plus noise plus interference), typically read in dBm, and is a power indicator — not a quality indicator.`,
    prerequisites: ['comm-basics', 'noise-floor', 'noise-figure'],
    intro: String.raw`<p>The <strong>Received Signal Strength Indicator (RSSI)</strong> is one of the most misused numbers in wireless engineering. It is <em>fundamentally a measurement of power</em> integrated over the receiver's measurement bandwidth, and it lumps together everything the antenna and front-end capture: the wanted signal, thermal noise, and any co-channel interference. Because it is cheap to measure (it falls out of the automatic-gain-control loop and the ADC statistics), every radio reports it — but a high RSSI does not guarantee a good link, and a low RSSI does not guarantee a bad one. The quantity that actually predicts bit-error performance is <strong>SNR</strong> (or SINR), which RSSI alone cannot deliver.</p><p>This topic builds RSSI rigorously: how it is defined, why vendors mangle it into integers, how to extract SNR from RSSI given the noise floor, how cellular refines the idea into RSRP/RSRQ/SINR, and why RSSI-based distance ranging is a trap.</p>`,
    sections: [
      {
        h: 'What RSSI actually measures',
        html: String.raw`<p>RSSI is an estimate of the <strong>total power delivered to the receiver</strong> within its measurement (channel) bandwidth <em>B</em>. Formally it is the integral of the power spectral density across the passband, referred to the antenna connector (or wherever the calibration reference plane sits):</p><p>$$P_{RSSI} = \int_{f_c - B/2}^{f_c + B/2} S(f)\, df = P_{signal} + P_{noise} + P_{interference}$$</p><p>Three consequences follow immediately:</p><ul><li><strong>It includes noise.</strong> Even with no transmitter present, a receiver still reports an RSSI equal to its noise floor. This is the <em>idle</em> or <em>background</em> RSSI.</li><li><strong>It includes interference.</strong> A strong co-channel jammer raises RSSI without improving — indeed while destroying — link quality.</li><li><strong>It is bandwidth-dependent.</strong> The same signal measured over a wider bandwidth captures more noise, so its RSSI (dominated by noise in the weak-signal regime) rises.</li></ul><div class="callout"><strong>Key mental model:</strong> RSSI answers "how much power is hitting my receiver?" It does <em>not</em> answer "how much of that power is the signal I want?" Only when the signal dominates the noise-plus-interference (high SNR) does RSSI approximate the wanted signal power.</div>`
      },
      {
        h: 'dBm, vendor integers, and calibration',
        html: String.raw`<p>RSSI is naturally a power in <strong>dBm</strong> (decibels relative to 1 milliwatt): $P_{dBm} = 10\log_{10}(P/1\,\text{mW})$. Real receivers, however, rarely report true dBm. The original IEEE 802.11 standard defined RSSI as a dimensionless integer from 0 to a vendor-chosen maximum (RSSI_Max), used only internally by the CCA (clear channel assessment) logic. The mapping from that integer to real dBm was left entirely to the vendor.</p><table class="data"><tr><th>Vendor</th><th>RSSI_Max</th><th>Meaning of the integer</th></tr><tr><td>Cisco</td><td>100</td><td>Roughly maps to a dBm range via a proprietary table</td></tr><tr><td>Atheros</td><td>60</td><td>Often RSSI (dB above noise floor), i.e. closer to SNR</td></tr><tr><td>Symbol/Zebra</td><td>31</td><td>Coarse 5-bit indicator</td></tr></table><p>This is why <strong>you cannot compare raw RSSI integers between chipsets</strong>. Some vendors report an approximate dBm, some report dB-above-noise-floor (effectively an SNR), and some report an uncalibrated count. Serious work requires either a documented conversion or a per-unit calibration against a signal generator.</p><div class="callout"><strong>Engineering practice:</strong> Calibrate by injecting known-power CW tones from a calibrated source across the operating band and temperature range, then build a lookup/curve-fit from reported RSSI to true dBm. Front-end gain drifts with temperature and varies unit-to-unit by several dB — this dominates ranging error.</div>`
      },
      {
        h: 'Why power is not quality',
        html: String.raw`<p>The demodulator's error rate depends on the ratio of signal energy to noise-plus-interference, not on absolute power. Consider two scenarios with identical RSSI = &minus;70 dBm:</p><table class="data"><tr><th>Scenario</th><th>Signal</th><th>Noise+Interf.</th><th>SNR/SINR</th><th>Link</th></tr><tr><td>Clean, weak-ish</td><td>&minus;70.04 dBm</td><td>&minus;90 dBm</td><td>&asymp; 20 dB</td><td>Excellent</td></tr><tr><td>Strong jammer</td><td>&minus;85 dBm</td><td>&minus;70.2 dBm</td><td>&asymp; &minus;15 dB</td><td>Dead</td></tr></table><p>Both read &minus;70 dBm on the RSSI meter (since total power is dominated by whichever term is larger), yet one link is perfect and the other is unusable. This is the crux: <strong>RSSI cannot distinguish signal from garbage.</strong> To judge quality you must separate the wanted-signal power from the noise-plus-interference power.</p>`
      },
      {
        h: 'Deriving SNR from RSSI and the noise floor',
        html: String.raw`<p>If interference is negligible, RSSI is signal-plus-noise. Knowing the receiver's <strong>noise floor</strong> lets you back out SNR. The thermal noise floor is:</p><p>$$N_{dBm} = -174 + 10\log_{10}(B) + NF$$</p><p>where &minus;174 dBm/Hz is kT at 290 K, <em>B</em> is the noise bandwidth in Hz, and <em>NF</em> is the receiver noise figure in dB. Then, in the linear domain:</p><p>$$P_{signal} = P_{RSSI} - P_{noise} \quad(\text{linear subtraction})$$</p><p>$$\text{SNR}_{dB} = 10\log_{10}\!\left(\frac{P_{RSSI,lin} - N_{lin}}{N_{lin}}\right)$$</p><p>In the high-SNR limit ($P_{RSSI}\gg N$) this simplifies to $\text{SNR}_{dB} \approx P_{RSSI,dBm} - N_{dBm}$. In the low-SNR limit RSSI floors at the noise level and the subtraction becomes ill-conditioned — small calibration errors produce huge SNR errors. That is precisely why weak-link ranging is unreliable.</p><div class="callout"><strong>Worked shortcut:</strong> RSSI = &minus;80 dBm, B = 20 MHz, NF = 6 dB. Noise floor = &minus;174 + 73 + 6 = &minus;95 dBm. SNR &approx; &minus;80 &minus; (&minus;95) = 15 dB (high-SNR approximation valid since signal is 15 dB above noise).</div>`
      },
      {
        h: 'RSRP, RSRQ, SINR — the cellular refinement',
        html: String.raw`<p>LTE/5G designers recognised RSSI's blindness and split it into cleaner metrics measured on the reference signals:</p><ul><li><strong>RSRP (Reference Signal Received Power):</strong> the linear average power of the resource elements carrying cell-specific reference signals, in dBm <em>per resource element</em>. It isolates the wanted-cell pilot power, independent of load and bandwidth — a true "signal power" metric. Typical range &minus;44 (excellent) to &minus;140 dBm (edge).</li><li><strong>RSSI (carrier RSSI):</strong> total wideband received power across all N resource blocks in the OFDM symbols carrying reference signals — signal + noise + interference + serving + neighbour cells.</li><li><strong>RSRQ (Reference Signal Received Quality):</strong> $\text{RSRQ} = N \cdot \dfrac{\text{RSRP}}{\text{RSSI}}$, where N is the number of resource blocks. It normalises RSRP by total power, so it degrades when interference or load rises even if RSRP is strong — a quality metric. Range roughly &minus;3 (good) to &minus;20 dB.</li><li><strong>SINR:</strong> $\dfrac{P_{signal}}{P_{noise}+P_{interference}}$ — the most direct predictor of achievable throughput and MCS selection. Not standardised for reporting the way RSRP/RSRQ are, but computed by every modem.</li></ul><p>The pattern generalises: <strong>a good power metric (RSRP) plus a good quality metric (RSRQ/SINR) beats a single conflated RSSI.</strong></p>`
      },
      {
        h: 'RSSI-based ranging and its pitfalls',
        html: String.raw`<p>The tempting idea: since power falls with distance ($P \propto d^{-n}$), invert the path-loss model to estimate distance from RSSI. The log-distance model gives:</p><p>$$\text{RSSI}(d) = \text{RSSI}(d_0) - 10\,n\log_{10}\!\left(\frac{d}{d_0}\right) + X_\sigma$$</p><p>where $X_\sigma$ is zero-mean log-normal shadowing (standard deviation $\sigma$ dB). Solving for d amplifies every error, and there are many:</p><ul><li><strong>Shadowing:</strong> $\sigma$ of 4-10 dB is common. Because distance depends exponentially on RSSI, a 6 dB error at n = 2 already corresponds to a 2&times; distance error.</li><li><strong>Multipath fading:</strong> constructive/destructive interference makes RSSI vary by 20+ dB over a wavelength — moving a phone a few centimetres changes RSSI dramatically.</li><li><strong>Unknown n:</strong> the path-loss exponent depends on the environment and is rarely known precisely.</li><li><strong>Calibration drift:</strong> per-device and per-temperature offsets bias every estimate.</li><li><strong>Antenna orientation / body loss:</strong> hand and body attenuation adds several dB of unmodelled loss.</li></ul><div class="callout"><strong>Practice:</strong> RSSI ranging is fine for coarse zone/proximity detection (near/far, room-level with heavy averaging and fingerprinting) but poor for metric-accurate positioning. For real distance use time-of-flight (RTT, FTM in 802.11mc, UWB), which measures delay, not power.</div>`
      },
      {
        h: 'Measurement mechanics and averaging',
        html: String.raw`<p>Physically, RSSI is often derived from the AGC gain setting (the front-end sets gain to keep the ADC at a target level; the gain needed is inversely proportional to input power) or computed directly from the digital samples as mean-square amplitude. Because instantaneous power fluctuates with fading and modulation, radios apply <strong>temporal averaging</strong> (moving average or IIR filter). This introduces a bias/latency tradeoff: long averaging smooths fading but lags rapid changes (e.g. during handover). Standards specify measurement windows and layer-3 filtering (e.g. LTE L3 filter coefficient) to make measurements comparable.</p><p>Reference-plane matters: RSSI referred to the antenna connector differs from RSSI at the ADC by the front-end gain and cable/connector losses. Always state where the number is referenced.</p>`
      },
      {
        h: 'What you should now understand',
        html: String.raw`<div class="callout tip"><p>The essential mental model you should leave with:</p>
        <ul>
          <li><strong>What RSSI is:</strong> total received power in the channel bandwidth — signal plus noise plus interference — a power metric, never a quality metric.</li>
          <li><strong>Why power is not quality:</strong> two links with identical RSSI can be excellent or dead; only SNR/SINR (the ratio, not the sum) predicts bit-error performance.</li>
          <li><strong>Getting SNR from RSSI:</strong> compute the noise floor $-174+10\log_{10}B+NF$, then subtract — but only trust the high-SNR shortcut when the signal sits well above the floor; near it, subtract in linear units.</li>
          <li><strong>Vendor integers don't compare:</strong> IEEE 802.11 left the integer-to-dBm mapping vendor-defined, so raw counts need calibration.</li>
          <li><strong>The cellular fix:</strong> RSRP (pure power) plus RSRQ/SINR (quality) beats a single conflated RSSI.</li>
          <li><strong>Ranging caution:</strong> shadowing, multipath, unknown $n$, and calibration drift make RSSI distance estimates unreliable — use time-of-flight (UWB, FTM) for metric accuracy, and always state the reference plane and bandwidth.</li>
        </ul></div>`
      }
    ],
    keyPoints: [
      String.raw`RSSI is total received power in the channel bandwidth: signal + noise + interference. It is a power metric, not a quality metric.`,
      String.raw`RSSI in true dBm requires calibration; raw vendor RSSI integers (0..RSSI_Max) are not comparable across chipsets.`,
      String.raw`Two links with identical RSSI can have opposite quality — SNR/SINR is what predicts BER, not absolute power.`,
      String.raw`Noise floor $N = -174 + 10\log_{10}(B) + NF$ dBm; SNR $\approx$ RSSI $-$ N in the high-SNR limit.`,
      String.raw`Wider measurement bandwidth captures more noise, raising the idle RSSI (noise floor rises 3 dB per doubling of B).`,
      String.raw`Cellular splits RSSI into RSRP (power), RSSI (wideband total), and RSRQ = N&middot;RSRP/RSSI (quality); SINR predicts throughput.`,
      String.raw`RSSI ranging via $\text{RSSI}=\text{RSSI}(d_0)-10n\log_{10}(d/d_0)+X_\sigma$ is corrupted by shadowing, multipath, unknown n, and calibration drift.`,
      String.raw`For accurate distance use time-of-flight (UWB, 802.11mc FTM), not RSSI.`,
      String.raw`RSSI floors at the noise level for weak signals, making low-SNR SNR-extraction ill-conditioned.`,
      String.raw`RSSI is frequently derived from the AGC loop and is temporally averaged, trading noise smoothing against tracking lag.`,
      String.raw`Always specify the reference plane (antenna connector vs ADC) and the measurement bandwidth when quoting RSSI.`
    ],
    diagram: [
      {
        svg: String.raw`<svg viewBox="0 0 540 240" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif"><rect x="0" y="0" width="540" height="240" fill="#1c232e"/><text x="270" y="24" fill="#e6edf3" font-size="15" text-anchor="middle">RSSI = Signal + Noise + Interference</text><rect x="60" y="60" width="120" height="120" fill="#4dabf7" opacity="0.85"/><text x="120" y="125" fill="#0b0f14" font-size="13" text-anchor="middle">Signal</text><rect x="200" y="120" width="120" height="60" fill="#ffa94d" opacity="0.85"/><text x="260" y="155" fill="#0b0f14" font-size="13" text-anchor="middle">Noise</text><rect x="340" y="90" width="120" height="90" fill="#ff6b6b" opacity="0.85"/><text x="400" y="140" fill="#0b0f14" font-size="12" text-anchor="middle">Interference</text><line x1="40" y1="180" x2="500" y2="180" stroke="#9aa7b5" stroke-width="1.5"/><text x="270" y="208" fill="#9aa7b5" font-size="12" text-anchor="middle">Meter sums all three — cannot tell them apart</text><text x="270" y="228" fill="#63e6be" font-size="12" text-anchor="middle">Only Signal/(Noise+Interf) = SINR predicts quality</text></svg>`,
        caption: 'RSSI conflates signal, noise, and interference into one power number; quality lives in the ratio, not the sum.'
      },
      {
        svg: String.raw`<svg viewBox="0 0 540 260" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif"><rect x="0" y="0" width="540" height="260" fill="#1c232e"/><text x="270" y="22" fill="#e6edf3" font-size="14" text-anchor="middle">RSSI vs distance (log-distance model)</text><line x1="60" y1="30" x2="60" y2="210" stroke="#9aa7b5"/><line x1="60" y1="210" x2="500" y2="210" stroke="#9aa7b5"/><text x="30" y="120" fill="#9aa7b5" font-size="11" transform="rotate(-90 30 120)">RSSI (dBm)</text><text x="280" y="238" fill="#9aa7b5" font-size="11" text-anchor="middle">log distance</text><polyline points="70,50 500,190" fill="none" stroke="#4dabf7" stroke-width="2.5"/><text x="300" y="95" fill="#4dabf7" font-size="11">mean: slope = -10n dB/decade</text><rect x="60" y="170" width="440" height="40" fill="#ffa94d" opacity="0.18"/><text x="120" y="200" fill="#ffa94d" font-size="11">noise floor: RSSI flattens here</text><g stroke="#b197fc" stroke-width="1" opacity="0.8"><line x1="150" y1="70" x2="150" y2="95"/><line x1="250" y1="105" x2="250" y2="135"/><line x1="350" y1="140" x2="350" y2="170"/></g><text x="360" y="55" fill="#b197fc" font-size="11">shadowing spread X&#963;</text></svg>`,
        caption: 'RSSI falls linearly with log-distance (slope -10n dB/decade) but scatters by the shadowing sigma and floors at the noise level.'
      },
      {
        svg: String.raw`<svg viewBox="0 0 540 200" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif"><rect x="0" y="0" width="540" height="200" fill="#1c232e"/><text x="270" y="22" fill="#e6edf3" font-size="14" text-anchor="middle">Same RSSI, different SNR</text><rect x="50" y="50" width="180" height="120" fill="none" stroke="#9aa7b5"/><rect x="70" y="60" width="140" height="90" fill="#4dabf7" opacity="0.8"/><rect x="70" y="150" width="140" height="12" fill="#ffa94d"/><text x="140" y="120" fill="#0b0f14" font-size="12" text-anchor="middle">Signal</text><text x="140" y="188" fill="#63e6be" font-size="12" text-anchor="middle">SNR = 20 dB</text><rect x="310" y="50" width="180" height="120" fill="none" stroke="#9aa7b5"/><rect x="330" y="120" width="140" height="30" fill="#4dabf7" opacity="0.8"/><rect x="330" y="60" width="140" height="60" fill="#ff6b6b" opacity="0.8"/><text x="400" y="95" fill="#0b0f14" font-size="12" text-anchor="middle">Interf.</text><text x="400" y="188" fill="#ff6b6b" font-size="12" text-anchor="middle">SINR = -15 dB</text></svg>`,
        caption: 'Identical RSSI (equal total bar height) hides wildly different SNR/SINR — the reason RSSI is not a quality metric.'
      }
    ],
    equations: [
      {
        title: 'RSSI as total power',
        tex: String.raw`$$P_{RSSI} = P_{signal} + P_{noise} + P_{interference}$$`,
        derivation: String.raw`<p>Power spectral densities of statistically independent contributions add. Integrating the total PSD over the measurement bandwidth yields the sum of the individual band-limited powers. RSSI reports this sum; it has no mechanism to separate the terms.</p>`
      },
      {
        title: 'Noise floor',
        tex: String.raw`$$N_{dBm} = -174 + 10\log_{10}(B) + NF$$`,
        derivation: String.raw`<p>Thermal noise power is $N = kTB$. At $T = 290$ K, $kT = 1.38\times10^{-23}\times290 = 4.0\times10^{-21}$ W/Hz $= 4.0\times10^{-18}$ mW/Hz $= -174$ dBm/Hz. Multiplying by bandwidth adds $10\log_{10}(B)$; the receiver's noise figure adds NF dB. Hence the sum.</p>`
      },
      {
        title: 'SNR from RSSI (exact)',
        tex: String.raw`$$\text{SNR}_{dB} = 10\log_{10}\!\left(\frac{10^{P_{RSSI}/10} - 10^{N/10}}{10^{N/10}}\right)$$`,
        derivation: String.raw`<p>Convert RSSI and noise floor from dBm to linear mW. Signal power is the linear difference $P_s = P_{RSSI,lin} - N_{lin}$ (assuming interference negligible). SNR is $P_s/N$; take $10\log_{10}$. In the high-SNR limit the $-10^{N/10}$ term is negligible and $\text{SNR}\approx P_{RSSI}-N$.</p>`
      },
      {
        title: 'Log-distance path model (RSSI form)',
        tex: String.raw`$$\text{RSSI}(d) = \text{RSSI}(d_0) - 10\,n\log_{10}\!\left(\frac{d}{d_0}\right) + X_\sigma$$`,
        derivation: String.raw`<p>Received power falls as $d^{-n}$, so in dB it drops by $10n\log_{10}(d/d_0)$ relative to a reference distance $d_0$. Shadowing adds a zero-mean Gaussian term $X_\sigma\sim\mathcal{N}(0,\sigma^2)$ in dB (log-normal in linear). Inverting for d divides by $10n$ and exponentiates, amplifying errors.</p>`
      },
      {
        title: 'RSRQ definition',
        tex: String.raw`$$\text{RSRQ} = \frac{N \cdot \text{RSRP}}{\text{RSSI}}$$`,
        derivation: String.raw`<p>RSRP is per-resource-element pilot power; carrier RSSI is total wideband power over N resource blocks. Scaling RSRP by N puts it on the same total-power footing, and the ratio measures the fraction of received power that is the wanted pilot — a load/interference-sensitive quality figure. Expressed in dB it is $10\log_{10}(N)+\text{RSRP}_{dBm}-\text{RSSI}_{dBm}$.</p>`
      },
      {
        title: 'Distance estimate from RSSI',
        tex: String.raw`$$\hat{d} = d_0 \cdot 10^{\frac{\text{RSSI}(d_0) - \text{RSSI}(d)}{10\,n}}$$`,
        derivation: String.raw`<p>Drop the shadowing term and solve the log-distance model for d. The exponent shows why a fixed RSSI error translates into a multiplicative distance error: an error $\Delta$ dB scales $\hat{d}$ by $10^{\Delta/10n}$. At $n=2$, 6 dB error &rarr; factor $10^{0.15}\approx1.4$; 12 dB &rarr; $\approx2\times$.</p>`
      }
    ],
    flashcards: [
      { front: String.raw`What does RSSI physically measure?`, back: String.raw`Total received power in the channel bandwidth: wanted signal + noise + interference, referred to a defined reference plane.` },
      { front: String.raw`Why is RSSI not a quality metric?`, back: String.raw`It sums signal and impairments; identical RSSI can correspond to excellent or dead links. Quality depends on the ratio SNR/SINR, not total power.` },
      { front: String.raw`Are raw RSSI integers comparable across chipsets?`, back: String.raw`No. IEEE 802.11 left RSSI as a vendor-defined 0..RSSI_Max integer; conversions to dBm (or dB-above-noise) differ per vendor and require calibration.` },
      { front: String.raw`How do you get SNR from RSSI?`, back: String.raw`Compute the noise floor $-174+10\log_{10}(B)+NF$; in the high-SNR limit SNR(dB) $\approx$ RSSI(dBm) $-$ noise floor(dBm). Exact: linear-subtract noise first.` },
      { front: String.raw`What is the thermal noise floor formula?`, back: String.raw`$N = -174\,\text{dBm/Hz} + 10\log_{10}(B) + NF$, where -174 is kT at 290 K.` },
      { front: String.raw`Define RSRP.`, back: String.raw`Reference Signal Received Power: linear average power of resource elements carrying cell-specific reference signals, in dBm per RE. A pure signal-power metric.` },
      { front: String.raw`Define RSRQ and what it captures.`, back: String.raw`$\text{RSRQ}=N\cdot\text{RSRP}/\text{RSSI}$. It normalises pilot power by total power, degrading under load/interference — a quality metric.` },
      { front: String.raw`What is SINR?`, back: String.raw`Signal power divided by (noise + interference) power. The most direct predictor of achievable modulation/coding and throughput.` },
      { front: String.raw`Why does RSSI-based ranging fail?`, back: String.raw`Shadowing (4-10 dB sigma), multipath (20+ dB over a wavelength), unknown path-loss exponent, and calibration drift — all amplified when inverting for distance.` },
      { front: String.raw`Effect of measurement bandwidth on idle RSSI?`, back: String.raw`Idle RSSI equals the noise floor, which rises 3 dB per doubling of bandwidth (10log10(B)).` },
      { front: String.raw`Where is RSSI usually derived from in hardware?`, back: String.raw`From the AGC gain setting (gain needed is inversely proportional to input power) or mean-square amplitude of the digital samples, then temporally averaged.` },
      { front: String.raw`Distance error from a 6 dB RSSI error at n=2?`, back: String.raw`$\hat d$ scales by $10^{6/(10\cdot2)}=10^{0.3}\approx2.0$, so roughly a 2&times; distance error.` },
      { front: String.raw`Preferred method for accurate distance?`, back: String.raw`Time-of-flight: UWB, 802.11mc Fine Timing Measurement (FTM), RTT — they measure propagation delay, not power.` },
      { front: String.raw`What must always accompany a quoted RSSI value?`, back: String.raw`The reference plane (antenna connector vs ADC) and the measurement/channel bandwidth, plus calibration status.` }
    ],
    mcqs: [
      { q: String.raw`Two links both report RSSI = &minus;72 dBm. Link A works perfectly; link B is unusable. The most likely explanation is:`, options: [String.raw`Link B's RSSI meter is broken`, String.raw`Link B has strong co-channel interference raising total power while degrading SINR`, String.raw`Link A has a higher path-loss exponent`, String.raw`RSSI is always wrong below &minus;70 dBm`], answer: 1, explain: String.raw`RSSI sums signal + noise + interference. A jammer can hold total power at &minus;72 dBm while the signal-to-(noise+interference) ratio is negative, killing the link.` },
      { q: String.raw`A receiver has B = 20 MHz and NF = 5 dB. Its noise floor is approximately:`, options: [String.raw`&minus;174 dBm`, String.raw`&minus;101 dBm`, String.raw`&minus;96 dBm`, String.raw`&minus;88 dBm`], answer: 2, explain: String.raw`$-174 + 10\log_{10}(20\times10^6) + 5 = -174 + 73 + 5 = -96$ dBm.` },
      { q: String.raw`RSSI = &minus;78 dBm with a &minus;96 dBm noise floor and negligible interference. Approximate SNR is:`, options: [String.raw`6 dB`, String.raw`18 dB`, String.raw`&minus;18 dB`, String.raw`174 dB`], answer: 1, explain: String.raw`High-SNR approximation: SNR &approx; &minus;78 &minus; (&minus;96) = 18 dB.` },
      { q: String.raw`Which metric best predicts achievable throughput / MCS selection?`, options: [String.raw`RSSI`, String.raw`RSRP`, String.raw`SINR`, String.raw`Idle noise floor`], answer: 2, explain: String.raw`SINR = signal / (noise + interference) directly drives the achievable Shannon rate and modulation/coding choice.` },
      { q: String.raw`RSRQ is defined as:`, options: [String.raw`RSRP &minus; RSSI in linear`, String.raw`$N\cdot\text{RSRP}/\text{RSSI}$`, String.raw`RSSI / noise floor`, String.raw`RSRP + NF`], answer: 1, explain: String.raw`RSRQ = N&middot;RSRP/RSSI, normalising pilot power by total received power over N resource blocks — a quality figure.` },
      { q: String.raw`Doubling the measurement bandwidth changes the idle (noise-only) RSSI by:`, options: [String.raw`0 dB`, String.raw`+3 dB`, String.raw`+6 dB`, String.raw`&minus;3 dB`], answer: 1, explain: String.raw`Noise power scales with B; $10\log_{10}(2)\approx3$ dB, so idle RSSI rises 3 dB.` },
      { q: String.raw`The dominant reason vendor RSSI integers are not comparable is:`, options: [String.raw`Different antenna colours`, String.raw`The standard left the integer-to-dBm mapping vendor-defined`, String.raw`RSSI is measured in watts by some vendors`, String.raw`RSSI is a frequency, not a power`], answer: 1, explain: String.raw`IEEE 802.11 specified RSSI only as an internal 0..RSSI_Max count; each vendor chose its own (often undocumented) mapping.` },
      { q: String.raw`At path-loss exponent n = 2, a 12 dB RSSI measurement error corresponds to roughly what distance error factor?`, options: [String.raw`1.2&times;`, String.raw`2&times;`, String.raw`4&times;`, String.raw`12&times;`], answer: 2, explain: String.raw`$\hat d$ scales by $10^{\Delta/(10n)} = 10^{12/(10\cdot2)} = 10^{0.6}\approx 4$, so a 12 dB error gives about a 4&times; distance error.` },
      { q: String.raw`Which is a true "signal power" metric that excludes interference and load?`, options: [String.raw`Carrier RSSI`, String.raw`RSRP`, String.raw`RSRQ`, String.raw`AGC gain`], answer: 1, explain: String.raw`RSRP measures only the reference-signal resource elements, isolating the wanted pilot power independent of load/interference.` },
      { q: String.raw`Why is extracting SNR from RSSI unreliable at low SNR?`, options: [String.raw`Noise floor becomes negative`, String.raw`RSSI floors at the noise level, so linear subtraction is ill-conditioned`, String.raw`SNR is undefined below 0 dB`, String.raw`Bandwidth becomes zero`], answer: 1, explain: String.raw`When signal is near or below the noise floor, RSSI &approx; noise, and $P_{RSSI,lin}-N_{lin}$ is a small difference of large numbers, hugely sensitive to calibration error.` },
      { q: String.raw`For accurate metric-level distance measurement you should use:`, options: [String.raw`RSSI trilateration`, String.raw`Time-of-flight (UWB / 802.11mc FTM)`, String.raw`RSRQ`, String.raw`Noise figure`], answer: 1, explain: String.raw`Time-of-flight measures propagation delay, which is far less corrupted by fading and calibration than power-based RSSI ranging.` },
      { q: String.raw`RSSI is commonly derived in hardware from:`, options: [String.raw`The transmit power register`, String.raw`The AGC gain setting or mean-square sample amplitude`, String.raw`The crystal oscillator frequency`, String.raw`The FEC decoder`], answer: 1, explain: String.raw`AGC gain needed to reach the ADC target is inversely related to input power; alternatively the digital samples' mean-square value gives power directly.` },
      { q: String.raw`A statement of RSSI is incomplete without specifying:`, options: [String.raw`The modulation order`, String.raw`The reference plane and measurement bandwidth`, String.raw`The FEC code rate`, String.raw`The symbol period`], answer: 1, explain: String.raw`RSSI depends on where it is referenced (antenna vs ADC) and on the bandwidth over which power is integrated.` }
    ],
    numericals: [
      { q: String.raw`A Wi-Fi receiver operates with a 40 MHz channel and NF = 6 dB. It reports RSSI = &minus;65 dBm with negligible interference. Find the noise floor and the SNR.`, solution: String.raw`<p><b>Formula.</b> $$N=-174+10\log_{10}B+NF,\qquad \mathrm{SNR}\approx \mathrm{RSSI}-N\ (\text{high-SNR}),$$ where $N$ is the noise floor (dBm), $B$ the bandwidth (Hz), $NF$ the noise figure (dB).</p><p><b>Substitute.</b> $N=-174+10\log_{10}(40\times10^{6})+6$; $\mathrm{SNR}=-65-N$.</p><p><b>Compute.</b> $10\log_{10}(4\times10^{7})=76.02$ dB, so $N=-174+76.02+6=-91.98\approx-92$ dBm. SNR $=-65-(-92)=27$ dB.</p><p><b>Explanation.</b> With the signal 27 dB above the floor the high-SNR approximation is valid (exact linear subtraction shifts it &lt;0.01 dB). A comfortable 27 dB SNR supports a high-order MCS on this wideband channel.</p>` },
      { q: String.raw`RSSI = &minus;90 dBm, noise floor = &minus;92 dBm. Compute the exact SNR and compare with the high-SNR approximation.`, solution: String.raw`<p><b>Formula.</b> Subtract noise in linear units first, then form the ratio: $$P_s=10^{\mathrm{RSSI}/10}-10^{N/10},\qquad \mathrm{SNR}=10\log_{10}\frac{P_s}{10^{N/10}}.$$</p><p><b>Substitute.</b> $P_{RSSI}=10^{-9.0}$ mW, $N=10^{-9.2}$ mW; $P_s=10^{-9.0}-10^{-9.2}$.</p><p><b>Compute.</b> $P_{RSSI}=1.0\times10^{-9}$, $N=6.31\times10^{-10}$, so $P_s=3.69\times10^{-10}$ mW. SNR $=10\log_{10}(3.69\times10^{-10}/6.31\times10^{-10})=10\log_{10}(0.585)=-2.3$ dB.</p><p><b>Explanation.</b> The high-SNR shortcut $-90-(-92)=+2$ dB is wrong by 4.3 dB. Near the noise floor RSSI is a small difference of large numbers, so you must subtract in linear units — this is why weak-signal SNR (and RSSI ranging) is ill-conditioned.</p>` },
      { q: String.raw`An LTE UE reports RSRP = &minus;95 dBm and carrier RSSI = &minus;65 dBm over N = 50 resource blocks. Compute RSRQ in dB.`, solution: String.raw`<p><b>Formula.</b> $$\mathrm{RSRQ}_{dB}=10\log_{10}N+\mathrm{RSRP}_{dBm}-\mathrm{RSSI}_{dBm},$$ from $\mathrm{RSRQ}=N\cdot\mathrm{RSRP}/\mathrm{RSSI}$, with $N$ the number of resource blocks.</p><p><b>Substitute.</b> $\mathrm{RSRQ}=10\log_{10}(50)+(-95)-(-65)$.</p><p><b>Compute.</b> $10\log_{10}(50)=16.99$ dB, so $\mathrm{RSRQ}=16.99-95+65=-13.0$ dB.</p><p><b>Explanation.</b> Around −13 dB is fair-to-poor quality. The 30 dB gap between wideband carrier RSSI and per-RE RSRP signals heavy load or interference in the band — RSRQ catches this even though RSRP alone might look acceptable.</p>` },
      { q: String.raw`Reference measurement: at $d_0 = 1$ m, RSSI $= -40$ dBm. Environment has n = 3. A node reports &minus;85 dBm. Estimate the distance.`, solution: String.raw`<p><b>Formula.</b> Invert the log-distance model for distance: $$\hat d=d_0\cdot 10^{(\mathrm{RSSI}(d_0)-\mathrm{RSSI})/(10n)},$$ with $d_0$ the reference distance and $n$ the path-loss exponent.</p><p><b>Substitute.</b> $\hat d=1\cdot 10^{(-40-(-85))/(10\times3)}=10^{45/30}$.</p><p><b>Compute.</b> $\hat d=10^{1.5}=31.6$ m. With $\pm6$ dB shadowing: $10^{(45\pm6)/30}=10^{1.3}$ to $10^{1.7}=20.0$ to $50.1$ m.</p><p><b>Explanation.</b> A single sigma of shadowing spreads the estimate over 20–50 m — a 2.5× range from one 6 dB uncertainty. This exponential error amplification is precisely why RSSI ranging is unreliable for metric accuracy.</p>` },
      { q: String.raw`A receiver's front end has 25 dB gain and a 2 dB cable loss ahead of it. The ADC-referenced RSSI reads &minus;40 dBm. What is the antenna-connector RSSI?`, solution: String.raw`<p><b>Formula.</b> Refer power back across the chain by subtracting the net gain between the planes: $$\mathrm{RSSI}_{ant}=\mathrm{RSSI}_{ADC}-(G_{LNA}-L_{cable}).$$</p><p><b>Substitute.</b> Net gain $=25-2=+23$ dB; $\mathrm{RSSI}_{ant}=-40-23$.</p><p><b>Compute.</b> $\mathrm{RSSI}_{ant}=-63$ dBm.</p><p><b>Explanation.</b> The antenna-connector signal is 23 dB weaker than the ADC-referenced reading because the front end amplifies it net +23 dB. This large offset is exactly why every RSSI figure must state its reference plane.</p>` },
      { q: String.raw`Given RSSI = &minus;70 dBm total, of which interference contributes &minus;72 dBm and noise floor is &minus;95 dBm, find the signal power and SINR.`, solution: String.raw`<p><b>Formula.</b> Work in linear power, isolate the signal, then form the ratio: $$P_s=P_{tot}-P_I-N,\qquad \mathrm{SINR}=10\log_{10}\frac{P_s}{P_I+N}.$$</p><p><b>Substitute.</b> $P_{tot}=10^{-7.0}$, $P_I=10^{-7.2}$, $N=10^{-9.5}$ mW; $P_s=10^{-7.0}-10^{-7.2}-10^{-9.5}$.</p><p><b>Compute.</b> $P_{tot}=1.0\times10^{-7}$, $P_I=6.31\times10^{-8}$, $N=3.16\times10^{-10}$, so $P_s=3.66\times10^{-8}$ mW $=-74.4$ dBm. $P_I+N=6.34\times10^{-8}$ mW, giving $\mathrm{SINR}=10\log_{10}(0.577)=-2.4$ dB.</p><p><b>Explanation.</b> Despite a healthy −70 dBm RSSI, SINR is negative — the link is interference-limited. This is the concrete demonstration that RSSI is a power metric, not a quality metric.</p>` }
    ],
    realWorld: String.raw`<p>RSSI drives everyday radio behaviour: Wi-Fi roaming thresholds, cellular handover triggers, LoRaWAN adaptive data rate, and the "bars" on your phone (a smoothed RSRP/RSSI mapping). Site-survey tools plot RSSI heatmaps for coverage planning, but experienced engineers overlay SNR/SINR because a green RSSI map can hide interference dead-zones. BLE beacons expose a calibrated "Tx power at 1 m" so apps can attempt RSSI proximity (near/immediate/far) — Apple's iBeacon does exactly this, and its coarse buckets reflect how untrustworthy fine RSSI ranging is. The industry's move to UWB (Apple U1/U2, FiRa) for precise ranging is a direct admission that RSSI, however convenient, cannot deliver metric accuracy.</p>`,
    related: ['noise-floor', 'noise-figure', 'link-budget', 'path-loss', 'comm-basics']
  },
  {
    id: 'path-loss',
    title: 'Path Loss',
    category: 'RF Link & Metrics',
    tags: ['path loss', 'friis', 'fspl', 'propagation', 'shadowing', 'fading', 'hata'],
    summary: String.raw`Path loss is the reduction in signal power density as a wave propagates, modelled by Friis free-space loss and extended with a path-loss exponent, log-normal shadowing, and multipath fading for real environments.`,
    prerequisites: ['comm-basics', 'antenna-gain', 'maxwell'],
    intro: String.raw`<p><strong>Path loss</strong> is the single largest term in almost every link budget: the attenuation a signal suffers travelling from transmit antenna to receive antenna. In free space it is governed exactly by the <strong>Friis transmission equation</strong>, which reveals the famous "inverse-square" spreading of power and a counter-intuitive frequency dependence. Real channels add three complications on top of the deterministic mean: a larger <strong>path-loss exponent</strong> from obstruction and ground reflection, slow <strong>log-normal shadowing</strong> from large obstacles, and fast <strong>multipath fading</strong> from constructive/destructive interference.</p><p>This topic derives Friis rigorously, decodes the $20\log_{10}(d)+20\log_{10}(f)+K$ formula, explains the "6 dB per octave" rules of thumb, and layers on the statistical models (log-distance, Okumura-Hata, COST-231) engineers actually use for coverage prediction.</p>`,
    sections: [
      {
        h: 'Free-space spreading and the Friis equation',
        html: String.raw`<p>An isotropic transmitter radiating power $P_t$ spreads that power over the surface of an expanding sphere. At distance d the <strong>power density</strong> is $P_t/(4\pi d^2)$ W/m². A transmit antenna with gain $G_t$ focuses power, multiplying density by $G_t$. The receive antenna captures power proportional to its <strong>effective aperture</strong> $A_e = G_r\lambda^2/(4\pi)$.</p><p>Multiplying density by aperture gives the <strong>Friis transmission equation</strong>:</p><p>$$P_r = P_t\, G_t\, G_r \left(\frac{\lambda}{4\pi d}\right)^2$$</p><p>The bracketed term is the reciprocal of the <strong>free-space path loss (FSPL)</strong>. Note the $\lambda^2$: higher frequency (smaller $\lambda$) means <em>more</em> loss for fixed antenna gains — but this is because a fixed-gain antenna has a smaller aperture at high frequency, not because the wave "attenuates" faster. Free space does not absorb; the loss is pure geometric spreading plus aperture shrinkage.</p><div class="callout"><strong>Subtlety:</strong> If instead you fix the <em>physical aperture</em> (e.g. a dish of area A), then $G=4\pi A/\lambda^2$ grows with frequency, and higher frequency actually gives <em>more</em> gain. The frequency dependence of "path loss" is entirely about which quantity you hold fixed.</div>`
      },
      {
        h: 'FSPL in decibels — the master formula',
        html: String.raw`<p>Taking $10\log_{10}$ of the reciprocal of the bracketed Friis term (with unity antenna gains) gives free-space path loss in dB:</p><p>$$\text{FSPL}_{dB} = 20\log_{10}(d) + 20\log_{10}(f) + K$$</p><p>The constant K absorbs $4\pi/c$ and the unit choices:</p><table class="data"><tr><th>Units of d, f</th><th>K</th></tr><tr><td>metres, Hz</td><td>&minus;147.55</td></tr><tr><td>km, MHz</td><td>32.44</td></tr><tr><td>km, GHz</td><td>92.45</td></tr><tr><td>miles, MHz</td><td>36.6</td></tr></table><p>The two $20\log_{10}$ terms are the heart of it: loss grows <strong>20 dB per decade of distance</strong> and <strong>20 dB per decade of frequency</strong>. Memorise the km/MHz form (32.44) and the km/GHz form (92.45) — most RF work uses one of these.</p>`
      },
      {
        h: 'The 6 dB per octave rules',
        html: String.raw`<p>A factor of 2 (an octave) in either distance or frequency changes FSPL by $20\log_{10}(2) = 6.02$ dB. So:</p><ul><li><strong>Double the distance &rarr; +6 dB path loss.</strong> (Quarter the received power — consistent with inverse-square.)</li><li><strong>Double the frequency &rarr; +6 dB path loss</strong> (at fixed antenna gains).</li><li>A decade (&times;10) gives +20 dB in each case.</li></ul><p>These are exam gold: you can do most FSPL comparisons in your head. Moving from 2.4 GHz to 5 GHz (roughly one octave) costs about 6 dB more path loss for the same gains — a key reason 5 GHz Wi-Fi has shorter range.</p><div class="callout"><strong>Reference anchors worth memorising:</strong> FSPL at 1 km, 1 GHz &approx; 92.4 dB. At 100 m, 2.4 GHz: $20\log(0.1)+20\log(2400)+32.44 = -20+67.6+32.44 = 80.0$ dB.</div>`
      },
      {
        h: 'The path-loss exponent and log-distance model',
        html: String.raw`<p>Real environments lose power faster than free space because of ground-reflection cancellation, diffraction, and absorption. We generalise the distance exponent from 2 to <strong>n</strong>:</p><p>$$PL(d)_{dB} = PL(d_0) + 10\,n\log_{10}\!\left(\frac{d}{d_0}\right)$$</p><p>$d_0$ is a reference distance (often 1 m indoors, 100 m or 1 km outdoors) where $PL(d_0)$ is measured or computed from FSPL. Typical exponents:</p><table class="data"><tr><th>Environment</th><th>n</th></tr><tr><td>Free space</td><td>2.0</td></tr><tr><td>Urban macrocell (LOS)</td><td>2.7 &ndash; 3.5</td></tr><tr><td>Urban (NLOS)</td><td>3.0 &ndash; 5.0</td></tr><tr><td>Indoor LOS</td><td>1.6 &ndash; 1.8</td></tr><tr><td>Indoor obstructed</td><td>4 &ndash; 6</td></tr><tr><td>Two-ray ground (far)</td><td>4.0</td></tr></table><p>Note the two-ray plane-earth model predicts $d^{-4}$ (n = 4) in the far region where direct and ground-reflected rays cancel — hence the common "40 dB/decade" outdoor slope. Indoor LOS can be <em>below</em> 2 due to waveguiding down corridors.</p>`
      },
      {
        h: 'Shadowing — log-normal large-scale fading',
        html: String.raw`<p>At a given distance, measured path loss scatters around the mean because of specific obstacles (buildings, trees, walls). Empirically this scatter is <strong>log-normal</strong>: Gaussian in dB. The full log-distance model with shadowing is:</p><p>$$PL(d) = PL(d_0) + 10\,n\log_{10}\!\left(\frac{d}{d_0}\right) + X_\sigma,\quad X_\sigma\sim\mathcal{N}(0,\sigma^2)$$</p><p>$\sigma$ (the shadowing standard deviation) is typically 4-6 dB outdoors and up to 8-12 dB indoors. Because it is Gaussian in dB, coverage design uses a <strong>fade margin</strong>: to guarantee coverage at the cell edge with probability p, add $Q^{-1}(1-p)\cdot\sigma$ dB of margin. For 95% edge coverage ($1.645\sigma$) at $\sigma=6$ dB, that is nearly 10 dB of margin.</p><div class="callout"><strong>Slow vs fast:</strong> Shadowing is "slow" (large-scale) fading — it varies over tens of metres as you pass different obstacles. Multipath is "fast" (small-scale) fading — it varies over a wavelength.</div>`
      },
      {
        h: 'Multipath and fast fading',
        html: String.raw`<p>Multiple reflected/scattered copies of the signal arrive with different delays and phases. Their vector sum fluctuates rapidly with position and frequency:</p><ul><li><strong>Rayleigh fading:</strong> no dominant line-of-sight; the envelope is Rayleigh-distributed, with deep nulls (20-30 dB) roughly every half wavelength.</li><li><strong>Rician fading:</strong> a strong LOS component plus scatter; parameterised by the K-factor (LOS power / scatter power). Large K &rarr; near-Gaussian, shallow fades.</li><li><strong>Frequency selectivity:</strong> when the delay spread exceeds the symbol period, different frequencies fade differently (frequency-selective fading), causing inter-symbol interference — the motivation for OFDM and equalisation.</li></ul><p>Fast fading is combated by diversity (space/time/frequency), spreading (DSSS/OFDM), and coding/interleaving, not by raw margin — a fixed margin cannot economically cover a 30 dB Rayleigh null.</p>`
      },
      {
        h: 'Empirical macrocell models: Okumura-Hata and COST-231',
        html: String.raw`<p>For cellular planning, closed-form FSPL is too optimistic; engineers use measurement-fitted models. <strong>Okumura-Hata</strong> (150-1500 MHz) gives urban path loss as a function of frequency, base-station height $h_b$, mobile height $h_m$, and distance, with correction terms for suburban/rural and city size. Its urban form is:</p><p>$$L_{urban} = 69.55 + 26.16\log_{10}f - 13.82\log_{10}h_b - a(h_m) + (44.9 - 6.55\log_{10}h_b)\log_{10}d$$</p><p><strong>COST-231 Hata</strong> extends this to 1500-2000 MHz (for GSM-1800/PCS) by changing constants (e.g. 46.3 + 33.9 log f ...) and adding a metropolitan correction $C_m$. Modern 5G planning uses 3GPP models (UMi, UMa, InH) and ray-tracing, but Hata/COST-231 remain the classic exam models. Note the distance term coefficient $(44.9 - 6.55\log h_b)$ implies an effective n around 3.5-4 for typical base-station heights.</p>`
      },
      {
        h: 'What you should now understand',
        html: String.raw`<div class="callout tip"><p>From first principles up to the empirical models:</p>
        <ul>
          <li><strong>Friis and FSPL:</strong> $P_r=P_tG_tG_r(\lambda/4\pi d)^2$; in dB, $\mathrm{FSPL}=20\log_{10}d+20\log_{10}f+K$ — free-space loss is geometric spreading plus aperture shrinkage, not absorption.</li>
          <li><strong>The 6 dB/octave rules:</strong> doubling distance OR frequency (at fixed gains) adds 6 dB; a decade adds 20 dB — enough to do most comparisons in your head.</li>
          <li><strong>The frequency subtlety:</strong> higher frequency loses more only because a fixed-gain antenna's aperture shrinks as $\lambda^2$; fix the physical aperture and the trend reverses.</li>
          <li><strong>Real environments:</strong> the log-distance model $PL(d_0)+10n\log_{10}(d/d_0)$ with $n$ from ~1.6 (indoor corridor) to 4-6 (obstructed) captures the mean; $n=4$ is the two-ray far-field slope.</li>
          <li><strong>Two random layers:</strong> slow log-normal shadowing (tens of metres, handled with a fade margin $Q^{-1}(1-p)\sigma$) and fast Rayleigh/Rician multipath (sub-wavelength, handled with diversity/OFDM/coding, not raw margin).</li>
          <li><strong>Engineering models:</strong> Okumura-Hata (150-1500 MHz) and COST-231 (1500-2000 MHz) fit measured macrocell loss; FSPL is always your first sanity check.</li>
        </ul></div>`
      }
    ],
    keyPoints: [
      String.raw`Friis: $P_r = P_t G_t G_r (\lambda/4\pi d)^2$ — free-space loss is geometric spreading plus receive-aperture shrinkage, not absorption.`,
      String.raw`FSPL(dB) $= 20\log_{10}(d) + 20\log_{10}(f) + K$; K = 32.44 (km, MHz), 92.45 (km, GHz), &minus;147.55 (m, Hz).`,
      String.raw`Loss increases 20 dB per decade (6 dB per octave) of distance AND of frequency at fixed antenna gains.`,
      String.raw`The frequency dependence is an artifact of fixed gain (aperture $\propto\lambda^2$); fixing physical aperture reverses it.`,
      String.raw`Log-distance model: $PL(d)=PL(d_0)+10n\log_{10}(d/d_0)$; n = 2 free space, 2.7-4 urban, 4-6 obstructed indoor.`,
      String.raw`Two-ray ground reflection gives n = 4 (40 dB/decade) in the far field.`,
      String.raw`Shadowing is log-normal (Gaussian in dB) with $\sigma$ 4-12 dB; add a fade margin $Q^{-1}(1-p)\sigma$ for target edge coverage.`,
      String.raw`Multipath fast fading (Rayleigh/Rician) varies over a wavelength; fought with diversity/OFDM/coding, not raw margin.`,
      String.raw`Slow (shadowing, tens of metres) vs fast (multipath, sub-wavelength) fading are distinct scales.`,
      String.raw`Okumura-Hata (150-1500 MHz) and COST-231 (1500-2000 MHz) are empirical macrocell models with height/frequency/distance terms.`,
      String.raw`Anchor: FSPL at 1 km & 1 GHz &approx; 92.4 dB; useful for quick mental checks.`
    ],
    diagram: [
      {
        svg: String.raw`<svg viewBox="0 0 540 240" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif"><defs><marker id="arr-pl-ray" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 Z" fill="#4dabf7"/></marker></defs><rect x="0" y="0" width="540" height="240" fill="#1c232e"/><text x="270" y="22" fill="#e6edf3" font-size="14" text-anchor="middle">Free-space spherical spreading</text><circle cx="70" cy="130" r="8" fill="#ffa94d"/><text x="70" y="160" fill="#9aa7b5" font-size="11" text-anchor="middle">Tx</text><g stroke="#4dabf7" fill="none" opacity="0.5"><path d="M78,130 A70,70 0 0,1 78,130.1"/><circle cx="70" cy="130" r="60"/><circle cx="70" cy="130" r="120"/><circle cx="70" cy="130" r="180"/></g><line x1="78" y1="130" x2="460" y2="130" stroke="#4dabf7" marker-end="url(#arr-pl-ray)"/><text x="150" y="120" fill="#9aa7b5" font-size="10">d</text><text x="270" y="120" fill="#9aa7b5" font-size="10">2d</text><text x="390" y="120" fill="#9aa7b5" font-size="10">3d</text><text x="270" y="210" fill="#63e6be" font-size="12" text-anchor="middle">Power density &#8733; 1/(4&#960;d&#178;)  &#8594;  double d = +6 dB loss</text></svg>`,
        caption: 'Power spreads over an expanding sphere; density falls as 1/d^2, giving the 6 dB-per-octave (20 dB/decade) distance rule.'
      },
      {
        svg: String.raw`<svg viewBox="0 0 540 280" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif"><rect x="0" y="0" width="540" height="280" fill="#1c232e"/><text x="270" y="20" fill="#e6edf3" font-size="14" text-anchor="middle">Path loss vs distance for various n</text><line x1="60" y1="30" x2="60" y2="230" stroke="#9aa7b5"/><line x1="60" y1="230" x2="500" y2="230" stroke="#9aa7b5"/><text x="30" y="130" fill="#9aa7b5" font-size="11" transform="rotate(-90 30 130)">PL (dB)</text><text x="280" y="258" fill="#9aa7b5" font-size="11" text-anchor="middle">log10(d)</text><polyline points="70,60 490,120" fill="none" stroke="#63e6be" stroke-width="2"/><text x="400" y="105" fill="#63e6be" font-size="11">n=2 free space</text><polyline points="70,60 490,170" fill="none" stroke="#4dabf7" stroke-width="2"/><text x="400" y="160" fill="#4dabf7" font-size="11">n=3 urban</text><polyline points="70,60 490,220" fill="none" stroke="#ff6b6b" stroke-width="2"/><text x="400" y="215" fill="#ff6b6b" font-size="11">n=4 two-ray</text><text x="150" y="55" fill="#9aa7b5" font-size="10">common ref d0</text></svg>`,
        caption: 'Steeper path-loss exponent n means faster power decay; n=4 (two-ray/obstructed) loses 40 dB per decade vs 20 for free space.'
      },
      {
        svg: String.raw`<svg viewBox="0 0 540 240" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif"><rect x="0" y="0" width="540" height="240" fill="#1c232e"/><text x="270" y="20" fill="#e6edf3" font-size="14" text-anchor="middle">Mean + shadowing + fast fading</text><line x1="50" y1="200" x2="510" y2="200" stroke="#9aa7b5"/><line x1="50" y1="30" x2="50" y2="200" stroke="#9aa7b5"/><text x="280" y="228" fill="#9aa7b5" font-size="11" text-anchor="middle">distance &#8594;</text><polyline points="60,70 500,150" fill="none" stroke="#63e6be" stroke-width="2.5"/><text x="330" y="105" fill="#63e6be" font-size="11">mean path loss</text><polyline points="60,72 120,62 180,95 240,110 300,105 360,135 420,150 500,158" fill="none" stroke="#ffa94d" stroke-width="1.5" opacity="0.9"/><text x="150" y="55" fill="#ffa94d" font-size="10">+ shadowing (slow)</text><polyline points="60,72 75,55 90,90 105,60 120,100 135,58 150,105 165,66 180,110 195,72 210,120 225,80 240,125 255,90 270,128" fill="none" stroke="#b197fc" stroke-width="1" opacity="0.85"/><text x="200" y="150" fill="#b197fc" font-size="10">+ fast fading (sub-&#955;)</text></svg>`,
        caption: 'Total received power = deterministic mean (log-distance) + slow log-normal shadowing + fast multipath fading, at three distinct scales.'
      }
    ],
    equations: [
      {
        title: 'Friis transmission equation',
        tex: String.raw`$$P_r = P_t\, G_t\, G_r \left(\frac{\lambda}{4\pi d}\right)^2$$`,
        derivation: String.raw`<p>Isotropic power density at d: $S = P_t/(4\pi d^2)$. Directive Tx multiplies by $G_t$. Received power = density &times; effective aperture: $P_r = S\,G_t\,A_e$ with $A_e = G_r\lambda^2/(4\pi)$. Substituting: $P_r = \dfrac{P_t G_t}{4\pi d^2}\cdot\dfrac{G_r\lambda^2}{4\pi} = P_t G_t G_r\left(\dfrac{\lambda}{4\pi d}\right)^2$.</p>`
      },
      {
        title: 'Free-space path loss (dB, unity gains)',
        tex: String.raw`$$\text{FSPL}_{dB} = 20\log_{10}(d) + 20\log_{10}(f) + 20\log_{10}\!\left(\frac{4\pi}{c}\right)$$`,
        derivation: String.raw`<p>FSPL $= (4\pi d/\lambda)^2 = (4\pi d f/c)^2$. In dB: $10\log_{10}(\cdot) = 20\log_{10}(4\pi d f/c) = 20\log d + 20\log f + 20\log(4\pi/c)$. Evaluating $20\log_{10}(4\pi/c)$ with $c=3\times10^8$: $= 20\log_{10}(4.19\times10^{-8}) = -147.55$ dB (metres, Hz). Unit conversion of d and f folds into K = 32.44 (km, MHz) or 92.45 (km, GHz).</p>`
      },
      {
        title: 'Log-distance path-loss model',
        tex: String.raw`$$PL(d)_{dB} = PL(d_0) + 10\,n\log_{10}\!\left(\frac{d}{d_0}\right) + X_\sigma$$`,
        derivation: String.raw`<p>Generalise the distance exponent: $P_r\propto d^{-n}$, so relative to $d_0$ the extra loss is $10n\log_{10}(d/d_0)$ dB. Anchor $PL(d_0)$ from FSPL or measurement. Add zero-mean Gaussian (dB) shadowing $X_\sigma$ for the log-normal scatter.</p>`
      },
      {
        title: 'Effective aperture',
        tex: String.raw`$$A_e = \frac{G_r\lambda^2}{4\pi}$$`,
        derivation: String.raw`<p>Reciprocity and the isotropic-radiator relation give the maximum effective aperture of a lossless antenna as $\lambda^2/4\pi$; multiplying by gain gives the actual aperture. This is the source of the $\lambda^2$ in Friis and hence of the "higher frequency = more loss (fixed gain)" behaviour.</p>`
      },
      {
        title: 'Fade margin for edge coverage',
        tex: String.raw`$$M_{fade} = Q^{-1}(1-p)\cdot\sigma$$`,
        derivation: String.raw`<p>Shadowing $X_\sigma\sim\mathcal{N}(0,\sigma^2)$ in dB. To keep received power above threshold with probability p at the cell edge, the mean must exceed threshold by $z\sigma$ where $z=Q^{-1}(1-p)$. For p = 0.95, $z = 1.645$; at $\sigma = 6$ dB, $M_{fade}\approx 9.9$ dB.</p>`
      },
      {
        title: 'Okumura-Hata urban',
        tex: String.raw`$$L = 69.55 + 26.16\log_{10}f - 13.82\log_{10}h_b - a(h_m) + (44.9 - 6.55\log_{10}h_b)\log_{10}d$$`,
        derivation: String.raw`<p>Empirical fit to Okumura's Tokyo measurements: f in MHz (150-1500), $h_b$ base height (m), $h_m$ mobile height, d in km. $a(h_m)$ is a mobile-antenna correction. The $\log_{10}d$ coefficient sets the effective slope (n &asymp; 3.5-4 for typical $h_b$). COST-231 re-fits constants for 1500-2000 MHz and adds a metropolitan term $C_m$.</p>`
      }
    ],
    flashcards: [
      { front: String.raw`State the Friis transmission equation.`, back: String.raw`$P_r = P_t G_t G_r (\lambda/4\pi d)^2$. Received power = transmit power &times; gains &times; the free-space spreading/aperture factor.` },
      { front: String.raw`Write FSPL in dB with the constant.`, back: String.raw`$\text{FSPL} = 20\log_{10}(d) + 20\log_{10}(f) + K$; K = 32.44 (km, MHz), 92.45 (km, GHz), &minus;147.55 (m, Hz).` },
      { front: String.raw`How much does FSPL change per octave of distance?`, back: String.raw`+6.02 dB (20log10(2)). Same for an octave of frequency at fixed gains. A decade gives +20 dB.` },
      { front: String.raw`Why does higher frequency mean more path loss at fixed gain?`, back: String.raw`Effective aperture $A_e = G\lambda^2/4\pi$ shrinks with $\lambda^2$; a fixed-gain antenna captures less power. It is not absorption.` },
      { front: String.raw`What happens to the frequency dependence if you fix physical aperture?`, back: String.raw`Gain $G=4\pi A/\lambda^2$ rises with frequency, so higher frequency gives more received power — the opposite trend.` },
      { front: String.raw`Give the log-distance path-loss model.`, back: String.raw`$PL(d)=PL(d_0)+10n\log_{10}(d/d_0)+X_\sigma$, with n the path-loss exponent and $X_\sigma$ log-normal shadowing.` },
      { front: String.raw`Typical path-loss exponents?`, back: String.raw`Free space 2; urban 2.7-3.5 (LOS) up to 5 (NLOS); indoor LOS 1.6-1.8; obstructed indoor 4-6; two-ray far field 4.` },
      { front: String.raw`What distribution is shadowing?`, back: String.raw`Log-normal — Gaussian in dB, zero mean, standard deviation sigma of about 4-6 dB outdoors, up to 8-12 dB indoors.` },
      { front: String.raw`Difference between shadowing and multipath fading?`, back: String.raw`Shadowing is slow/large-scale (varies over tens of metres from obstacles); multipath is fast/small-scale (varies over a wavelength from interference of reflections).` },
      { front: String.raw`Rayleigh vs Rician fading?`, back: String.raw`Rayleigh: no dominant LOS, deep nulls. Rician: strong LOS plus scatter, parameterised by K-factor; large K approaches non-fading.` },
      { front: String.raw`What does the two-ray ground model predict for the far-field slope?`, back: String.raw`n = 4 (40 dB per decade), because direct and ground-reflected rays partially cancel with distance.` },
      { front: String.raw`Frequency range of Okumura-Hata vs COST-231?`, back: String.raw`Hata: 150-1500 MHz. COST-231 Hata extension: 1500-2000 MHz (GSM-1800/PCS), with a metropolitan correction term.` },
      { front: String.raw`Fade margin for 95% edge coverage at sigma = 8 dB?`, back: String.raw`$1.645\times8\approx13.2$ dB.` },
      { front: String.raw`Quick anchor: FSPL at 1 km, 1 GHz?`, back: String.raw`Using km/MHz: $20\log(1)+20\log(1000)+32.44 = 0+60+32.44 = 92.44$ dB.` }
    ],
    mcqs: [
      { q: String.raw`Doubling the distance in free space changes path loss by:`, options: [String.raw`+3 dB`, String.raw`+6 dB`, String.raw`+12 dB`, String.raw`+20 dB`], answer: 1, explain: String.raw`$20\log_{10}(2) = 6.02$ dB. Inverse-square spreading: quarter the power.` },
      { q: String.raw`In Friis, received power at fixed antenna gains scales with frequency as:`, options: [String.raw`$f^2$`, String.raw`$1/f^2$`, String.raw`$1/f$`, String.raw`independent of f`], answer: 1, explain: String.raw`$P_r\propto\lambda^2 \propto 1/f^2$; higher frequency, less received power, because aperture shrinks as $\lambda^2$.` },
      { q: String.raw`FSPL at 100 m and 2.4 GHz (km/MHz form) is approximately:`, options: [String.raw`60 dB`, String.raw`80 dB`, String.raw`92 dB`, String.raw`110 dB`], answer: 1, explain: String.raw`$20\log(0.1)+20\log(2400)+32.44 = -20 + 67.6 + 32.44 = 80.0$ dB.` },
      { q: String.raw`A path-loss exponent of 4 corresponds to a slope of:`, options: [String.raw`20 dB/decade`, String.raw`40 dB/decade`, String.raw`4 dB/decade`, String.raw`10 dB/decade`], answer: 1, explain: String.raw`Slope = 10n dB/decade = 40 dB/decade, matching the two-ray ground model far field.` },
      { q: String.raw`The free-space constant K for kilometres and gigahertz is:`, options: [String.raw`32.44`, String.raw`92.45`, String.raw`&minus;147.55`, String.raw`36.6`], answer: 1, explain: String.raw`92.45 for km and GHz; 32.44 for km and MHz; &minus;147.55 for metres and Hz.` },
      { q: String.raw`Shadowing is best described as:`, options: [String.raw`Uniform random loss`, String.raw`Log-normal (Gaussian in dB) large-scale variation`, String.raw`Rayleigh fast fading`, String.raw`Deterministic 6 dB steps`], answer: 1, explain: String.raw`Large obstacles cause slow, log-normal (Gaussian-in-dB) scatter around the mean path loss.` },
      { q: String.raw`Which environment can have a path-loss exponent below 2?`, options: [String.raw`Dense urban NLOS`, String.raw`Indoor corridor (waveguiding) LOS`, String.raw`Rural macrocell`, String.raw`Two-ray ground`], answer: 1, explain: String.raw`Corridors act as waveguides, confining energy and giving n as low as 1.6-1.8.` },
      { q: String.raw`Fast fading (Rayleigh) deep nulls occur roughly every:`, options: [String.raw`Half wavelength`, String.raw`Ten wavelengths`, String.raw`One kilometre`, String.raw`One symbol period`], answer: 0, explain: String.raw`Multipath interference nulls recur on the order of half a wavelength of spatial displacement.` },
      { q: String.raw`Free-space "path loss" is caused primarily by:`, options: [String.raw`Atmospheric absorption`, String.raw`Geometric spreading plus receive-aperture shrinkage`, String.raw`Ohmic loss in the medium`, String.raw`Doppler shift`], answer: 1, explain: String.raw`Vacuum does not absorb; loss is spreading of power over a sphere and the $\lambda^2$ aperture term.` },
      { q: String.raw`Going from 2.4 GHz to 4.8 GHz (one octave) at fixed gains adds about:`, options: [String.raw`3 dB`, String.raw`6 dB`, String.raw`12 dB`, String.raw`20 dB`], answer: 1, explain: String.raw`One octave of frequency = $20\log_{10}(2)\approx6$ dB extra FSPL.` },
      { q: String.raw`COST-231 Hata extends Okumura-Hata to which band?`, options: [String.raw`30-300 MHz`, String.raw`150-1500 MHz`, String.raw`1500-2000 MHz`, String.raw`3-30 GHz`], answer: 2, explain: String.raw`COST-231 adapts Hata for 1500-2000 MHz (GSM-1800/PCS) with a metropolitan correction.` },
      { q: String.raw`For 90% edge coverage with sigma = 6 dB, the fade margin is about (Q^-1(0.10)=1.28):`, options: [String.raw`3 dB`, String.raw`7.7 dB`, String.raw`12 dB`, String.raw`0 dB`], answer: 1, explain: String.raw`$1.28\times6 = 7.7$ dB.` },
      { q: String.raw`Which technique best combats frequency-selective multipath?`, options: [String.raw`Adding raw fade margin`, String.raw`OFDM with per-subcarrier equalisation`, String.raw`Increasing carrier frequency`, String.raw`Lowering antenna gain`], answer: 1, explain: String.raw`OFDM turns a frequency-selective channel into many flat-faded subcarriers, each easily equalised; margin alone cannot cover deep nulls economically.` }
    ],
    numericals: [
      { q: String.raw`Compute FSPL for a 5.8 GHz link at 2 km using the km/GHz constant.`, solution: String.raw`<p><b>Formula.</b> $$\mathrm{FSPL}_{dB}=20\log_{10}d_{km}+20\log_{10}f_{GHz}+92.45,$$ where the constant 92.45 fixes the units to km and GHz.</p><p><b>Substitute.</b> $\mathrm{FSPL}=20\log_{10}(2)+20\log_{10}(5.8)+92.45$.</p><p><b>Compute.</b> $20\log_{10}(2)=6.02$; $20\log_{10}(5.8)=15.27$. $\mathrm{FSPL}=6.02+15.27+92.45=113.7$ dB.</p><p><b>Explanation.</b> About 114 dB of free-space loss over just 2 km at 5.8 GHz — a sanity check for any 5.8 GHz link. Measured loss far below this signals a measurement error; far above it means obstruction.</p>` },
      { q: String.raw`A 900 MHz link over 10 km in an urban area with n = 3.5, referenced to FSPL at d0 = 1 km. Find total path loss.`, solution: String.raw`<p><b>Formula.</b> Anchor at $d_0$ with FSPL, then extend with the path-loss exponent: $$PL(d)=\mathrm{FSPL}(d_0)+10\,n\log_{10}\frac{d}{d_0},\ \ \mathrm{FSPL}=20\log_{10}d_{km}+20\log_{10}f_{MHz}+32.44.$$</p><p><b>Substitute.</b> $\mathrm{FSPL}(1\,\mathrm{km})=20\log_{10}(1)+20\log_{10}(900)+32.44$; extra $=10\times3.5\times\log_{10}(10/1)$.</p><p><b>Compute.</b> $\mathrm{FSPL}(1\,\mathrm{km})=0+59.08+32.44=91.5$ dB; extra $=35\times1=35$ dB. Total $=91.5+35=126.5$ dB.</p><p><b>Explanation.</b> The urban exponent $n=3.5$ adds 35 dB over the decade from 1 to 10 km, versus only 20 dB in free space — a 15 dB penalty from clutter that a coverage plan must budget for.</p>` },
      { q: String.raw`Given $P_t = 20$ dBm, $G_t = G_r = 6$ dBi, FSPL = 100 dB, find the received power.`, solution: String.raw`<p><b>Formula.</b> The Friis equation in dB: $$P_r=P_t+G_t+G_r-\mathrm{FSPL},$$ with powers in dBm and gains/loss in dB.</p><p><b>Substitute.</b> $P_r=20+6+6-100$.</p><p><b>Compute.</b> $P_r=-68$ dBm.</p><p><b>Explanation.</b> Antenna gains contribute a modest +12 dB while path loss dominates at −100 dB — the received power lands at −68 dBm. This term-by-term addition is the essence of every link budget.</p>` },
      { q: String.raw`A system needs 95% cell-edge coverage. Measured shadowing sigma = 7 dB. What fade margin is required (Q^-1(0.05)=1.645)?`, solution: String.raw`<p><b>Formula.</b> For log-normal shadowing, the fade margin for edge-coverage probability $p$ is $$M_{fade}=Q^{-1}(1-p)\cdot\sigma,$$ with $\sigma$ the shadowing standard deviation in dB.</p><p><b>Substitute.</b> $M_{fade}=1.645\times7$.</p><p><b>Compute.</b> $M_{fade}=11.5$ dB.</p><p><b>Explanation.</b> The budget must carry about 11.5 dB above the mean-path-loss prediction so that 95% of edge locations stay above threshold despite obstacle-driven scatter. Higher target reliability or larger $\sigma$ demands proportionally more margin.</p>` },
      { q: String.raw`Using Friis directly: $P_t = 1$ W, $G_t = G_r = 1$ (isotropic), f = 2.4 GHz, d = 500 m. Find $P_r$ in dBm.`, solution: String.raw`<p><b>Formula.</b> The linear Friis equation with $\lambda=c/f$: $$P_r=P_t\,G_t\,G_r\left(\frac{\lambda}{4\pi d}\right)^2.$$</p><p><b>Substitute.</b> $\lambda=3\times10^{8}/2.4\times10^{9}=0.125$ m; $(\lambda/4\pi d)^2=(0.125/(4\pi\times500))^2$.</p><p><b>Compute.</b> $(0.125/6283.2)^2=(1.989\times10^{-5})^2=3.96\times10^{-10}$. $P_r=1\times3.96\times10^{-10}$ W $=3.96\times10^{-7}$ mW $=10\log_{10}(3.96\times10^{-7})=-64.0$ dBm.</p><p><b>Explanation.</b> The dB route confirms it: $\mathrm{FSPL}=20\log_{10}(0.5)+20\log_{10}(2400)+32.44=94.0$ dB, so $P_r=30-94=-64$ dBm. Linear-Friis and dB-FSPL agree, as they must.</p>` },
      { q: String.raw`How many dB more path loss does moving from 2 km to 8 km add in free space?`, solution: String.raw`<p><b>Formula.</b> Free-space loss scales with distance as $$\Delta\mathrm{FSPL}=20\log_{10}\frac{d_2}{d_1}.$$</p><p><b>Substitute.</b> $\Delta\mathrm{FSPL}=20\log_{10}(8/2)=20\log_{10}(4)$.</p><p><b>Compute.</b> $\Delta\mathrm{FSPL}=12.0$ dB (equivalently two octaves × 6 dB).</p><p><b>Explanation.</b> Quadrupling range adds 12 dB, consistent with the 6 dB-per-octave rule. This lets you compare link distances mentally without recomputing the full FSPL each time.</p>` },
      { q: String.raw`An indoor link at 1 m has PL(1 m) = 40 dB. Environment n = 3.5, shadowing sigma = 8 dB. Find the path loss at 30 m exceeded no more than 10% of the time (Q^-1(0.10)=1.28).`, solution: String.raw`<p><b>Formula.</b> Mean path loss plus a shadowing percentile term: $$PL_{mean}=PL(d_0)+10\,n\log_{10}\frac{d}{d_0},\qquad PL_{90\%}=PL_{mean}+Q^{-1}(0.10)\,\sigma.$$</p><p><b>Substitute.</b> $PL_{mean}=40+10\times3.5\times\log_{10}(30/1)$; percentile add $=1.28\times8$.</p><p><b>Compute.</b> $PL_{mean}=40+35\times1.477=91.7$ dB; add $10.2$ dB. $PL_{90\%}=91.7+10.2=101.9$ dB.</p><p><b>Explanation.</b> To serve 90% of locations at 30 m the design must tolerate about 102 dB — the extra 10 dB over the mean is the shadowing reserve. Skipping this term would leave a tenth of locations unserved.</p>` }
    ],
    realWorld: String.raw`<p>Path-loss models underpin cell planning, Wi-Fi AP placement, satellite link design, and radar range equations. Cellular operators run drive tests to fit local path-loss exponents and shadowing sigma, then feed them into planning tools (Atoll, WinProp) alongside ray tracing for dense urban 5G at mmWave, where oxygen/rain absorption and building blockage make n and blockage models critical. The 6 dB/octave frequency rule explains real deployment choices: sub-GHz IoT (LoRa, NB-IoT) trades data rate for range, while mmWave 5G accepts brutal path loss in exchange for bandwidth, compensated by massive-MIMO beamforming gain. FSPL is also the sanity check every RF engineer does first — if your measured loss is far below FSPL, you have a measurement error; if far above, you have obstruction or the wrong model.</p>`,
    related: ['link-budget', 'rssi', 'antenna-gain', 'comm-basics', 'noise-floor']
  },
  {
    id: 'link-budget',
    title: 'Link Budget',
    category: 'RF Link & Metrics',
    tags: ['link budget', 'eirp', 'sensitivity', 'margin', 'snr', 'coding gain', 'fade margin'],
    summary: String.raw`A link budget accounts for every gain and loss between transmitter and receiver to compute received power, compare it against sensitivity, and size the link margin.`,
    prerequisites: ['path-loss', 'rssi', 'noise-figure', 'noise-floor'],
    intro: String.raw`<p>A <strong>link budget</strong> is the accountant's ledger of a radio link: every decibel of gain (amplifiers, antennas) is a credit, every decibel of loss (cables, path loss, fading) is a debit, and the bottom line is the <strong>received signal power</strong> at the demodulator. Compare that to the <strong>receiver sensitivity</strong> — the minimum power for acceptable performance — and the difference is the <strong>link margin</strong>: your insurance against fading, rain, pointing error, and modelling optimism.</p><p>Because it is done entirely in dB (turning multiplications into additions), a link budget is fast to compute and audit. This topic builds the full equation term by term, derives receiver sensitivity from the noise floor and required SNR, explains EIRP and margin, and works a complete end-to-end example table. Mastering link budgets is the capstone of RF link engineering — it ties together path loss, noise, antennas, and coding into a single go/no-go number.</p>`,
    sections: [
      {
        h: 'The master link-budget equation',
        html: String.raw`<p>Working in dB, the received power is the transmit power plus all gains minus all losses:</p><p>$$P_{rx} = P_{tx} + G_{tx} - L_{tx} - PL - L_{misc} + G_{rx} - L_{rx}$$</p><table class="data"><tr><th>Term</th><th>Meaning</th><th>Units</th></tr><tr><td>$P_{tx}$</td><td>Transmit power at PA output</td><td>dBm</td></tr><tr><td>$G_{tx}$</td><td>Transmit antenna gain</td><td>dBi</td></tr><tr><td>$L_{tx}$</td><td>Tx feeder/connector/duplexer loss</td><td>dB</td></tr><tr><td>$PL$</td><td>Propagation path loss</td><td>dB</td></tr><tr><td>$L_{misc}$</td><td>Polarisation, pointing, atmospheric, body loss</td><td>dB</td></tr><tr><td>$G_{rx}$</td><td>Receive antenna gain</td><td>dBi</td></tr><tr><td>$L_{rx}$</td><td>Rx feeder/connector loss</td><td>dB</td></tr></table><p>Everything is a straight sum. The art is enumerating every real loss (engineers routinely forget connector, polarisation-mismatch, and pointing losses) and using a defensible path-loss model.</p>`
      },
      {
        h: 'EIRP — effective isotropic radiated power',
        html: String.raw`<p><strong>EIRP</strong> bundles the transmit side into one number: the power an isotropic radiator would need to produce the same field in the peak direction.</p><p>$$\text{EIRP} = P_{tx} + G_{tx} - L_{tx}\quad(\text{dBm})$$</p><p>It is what regulators cap (e.g. FCC limits 2.4 GHz Wi-Fi EIRP to +36 dBm) and what determines coverage on the transmit side. A related receive-side figure of merit is <strong>G/T</strong> (gain-to-noise-temperature ratio, dB/K), used for satellite earth stations, which combines receive antenna gain and system noise temperature into one quality metric. Using EIRP the link budget compresses to:</p><p>$$P_{rx} = \text{EIRP} - PL - L_{misc} + G_{rx} - L_{rx}$$</p>`
      },
      {
        h: 'Receiver sensitivity from the noise floor',
        html: String.raw`<p>The receiver works only if the received signal exceeds a minimum level — the <strong>sensitivity</strong>. It is built up from the thermal noise floor plus the noise figure plus the demodulator's required SNR:</p><p>$$P_{sens} = \underbrace{-174 + 10\log_{10}(B) + NF}_{\text{noise floor}} + \text{SNR}_{req}$$</p><p>The first three terms are the noise power at the receiver input; adding the required SNR gives the minimum signal power that yields the target error rate. $\text{SNR}_{req}$ depends on the modulation and coding: it is set by the required $E_b/N_0$ for the target BER, adjusted by spectral efficiency, and reduced by coding gain.</p><div class="callout"><strong>Worked sensitivity:</strong> B = 1 MHz, NF = 4 dB, QPSK needing SNR_req = 10 dB. Noise floor = &minus;174 + 60 + 4 = &minus;110 dBm. Sensitivity = &minus;110 + 10 = &minus;100 dBm.</div><p>Note sensitivity worsens (rises) with wider bandwidth, higher NF, or higher-order modulation (which needs more SNR). This is the fundamental tension: bandwidth buys data rate but costs sensitivity.</p>`
      },
      {
        h: 'From Eb/N0 and SNR to required SNR',
        html: String.raw`<p>The demodulator's fundamental requirement is expressed as $E_b/N_0$ (energy per bit over noise density) for a target BER. Converting to a channel SNR over bandwidth B and bit rate $R_b$:</p><p>$$\text{SNR} = \frac{E_b}{N_0}\cdot\frac{R_b}{B}$$</p><p>The ratio $R_b/B$ is the spectral efficiency (bits/s/Hz). Higher-order modulation packs more bits per Hz but needs a higher $E_b/N_0$ for the same BER, so $\text{SNR}_{req}$ climbs sharply — 64-QAM needs roughly 12-14 dB more SNR than BPSK for the same BER. <strong>Coding gain</strong> reduces the required $E_b/N_0$ (e.g. a good LDPC/turbo code gives 5-8 dB of coding gain near the target BER), directly lowering $\text{SNR}_{req}$ and thus improving sensitivity for free (at the cost of overhead/latency).</p>`
      },
      {
        h: 'Link margin and headroom budgeting',
        html: String.raw`<p>The <strong>link margin</strong> is how much the received power exceeds sensitivity:</p><p>$$M = P_{rx} - P_{sens}$$</p><p>A positive margin means the link closes; a negative margin means it fails. But the raw margin must cover several stochastic and worst-case impairments that the deterministic path loss omits:</p><ul><li><strong>Fade margin (shadowing):</strong> $Q^{-1}(1-p)\sigma$ dB for target coverage probability (e.g. 8-12 dB).</li><li><strong>Rain fade:</strong> critical above ~10 GHz; can be tens of dB at Ka-band for high availability (99.99%).</li><li><strong>Multipath/fast-fading margin:</strong> a few dB, or handled by diversity/coding.</li><li><strong>Pointing/tracking loss:</strong> for directional/steerable antennas, misalignment costs dB.</li><li><strong>Ageing/temperature/implementation loss:</strong> a couple of dB of engineering conservatism.</li></ul><div class="callout"><strong>Design rule:</strong> A link with, say, 30 dB of raw margin that must reserve 12 (fade) + 10 (rain) + 3 (pointing) + 2 (impl) = 27 dB has only 3 dB of true operating margin — barely closing. Always separate raw margin from allocated headroom.</div>`
      },
      {
        h: 'Trading power, antenna gain, and coding',
        html: String.raw`<p>Once a budget is short by X dB, there are three levers, each with different cost/consequence:</p><table class="data"><tr><th>Lever</th><th>Effect</th><th>Cost / constraint</th></tr><tr><td>Raise Tx power</td><td>+dB directly on EIRP</td><td>Regulatory EIRP cap, PA cost/power, battery, interference to others</td></tr><tr><td>Increase antenna gain</td><td>+dB on both EIRP and G_rx</td><td>Narrower beamwidth &rarr; pointing/tracking harder; size/weight</td></tr><tr><td>Add coding gain / lower modulation order</td><td>Lowers SNR_req &rarr; better sensitivity</td><td>Reduces data rate (overhead / fewer bits per symbol), adds latency</td></tr><tr><td>Reduce bandwidth</td><td>Lowers noise floor &rarr; better sensitivity</td><td>Reduces data rate</td></tr></table><p>The elegant insight: <strong>every one of these trades data rate, power, or hardware complexity for link margin</strong>, and Shannon capacity $C = B\log_2(1+\text{SNR})$ frames the ultimate limit. Antenna gain is often the cheapest dB (passive, bidirectional benefit) which is why beamforming/MIMO dominates modern designs, but it demands accurate pointing.</p>`
      },
      {
        h: 'A complete end-to-end worked link budget',
        html: String.raw`<p>Consider a 2.4 GHz point-to-point link at 5 km. Full ledger:</p><table class="data"><tr><th>Line item</th><th>Value</th><th>Running total (dBm)</th></tr><tr><td>Tx power $P_{tx}$</td><td>+20 dBm</td><td>+20.0</td></tr><tr><td>Tx cable/connector loss $L_{tx}$</td><td>&minus;1.5 dB</td><td>+18.5</td></tr><tr><td>Tx antenna gain $G_{tx}$</td><td>+14 dBi</td><td>+32.5 (= EIRP)</td></tr><tr><td>Free-space path loss (5 km, 2.4 GHz)</td><td>&minus;114.0 dB</td><td>&minus;81.5</td></tr><tr><td>Misc loss (polarisation+pointing) $L_{misc}$</td><td>&minus;3.0 dB</td><td>&minus;84.5</td></tr><tr><td>Rx antenna gain $G_{rx}$</td><td>+14 dBi</td><td>&minus;70.5</td></tr><tr><td>Rx cable loss $L_{rx}$</td><td>&minus;1.5 dB</td><td>&minus;72.0 (= $P_{rx}$)</td></tr></table><p>FSPL check: $20\log(5)+20\log(2400)+32.44 = 13.98+67.6+32.44 = 114.0$ dB. So $P_{rx} = -72.0$ dBm.</p><p><strong>Sensitivity:</strong> B = 20 MHz, NF = 6 dB, SNR_req = 15 dB (for the chosen MCS). Noise floor = &minus;174 + 73 + 6 = &minus;95 dBm; sensitivity = &minus;95 + 15 = &minus;80 dBm.</p><p><strong>Margin:</strong> $M = P_{rx} - P_{sens} = -72.0 - (-80) = +8.0$ dB.</p><p>Now allocate headroom: if we need 6 dB fade margin, only 2 dB of true operating margin remains. Verdict: the link closes but is marginal — raise antenna gain or lower the MCS (reduce SNR_req) to build robustness.</p>`
      },
      {
        h: 'What you should now understand',
        html: String.raw`<div class="callout tip"><p>The capstone that ties path loss, noise, antennas, and coding together:</p>
        <ul>
          <li><strong>The ledger:</strong> $P_{rx}=P_{tx}+G_{tx}-L_{tx}-PL-L_{misc}+G_{rx}-L_{rx}$ — every gain a credit, every loss a debit, all in dB so multiplications become sums.</li>
          <li><strong>EIRP:</strong> $P_{tx}+G_{tx}-L_{tx}$ bundles the transmit side and is what regulators cap; G/T is its receive-side counterpart for satellite links.</li>
          <li><strong>Sensitivity:</strong> $-174+10\log_{10}B+NF+\mathrm{SNR}_{req}$ sets the minimum usable signal; $\mathrm{SNR}_{req}=(E_b/N_0)(R_b/B)$ links it to modulation and coding.</li>
          <li><strong>Margin:</strong> $M=P_{rx}-P_{sens}$ must close positive, and raw margin has to be partitioned into fade, rain, pointing, and implementation reserves — a big-looking margin can be nearly all spoken for.</li>
          <li><strong>The three levers:</strong> Tx power (regulatory/battery limited), antenna gain (passive, helps both ends, but narrows the beam), and coding/lower modulation (trades data rate) — Shannon $C=B\log_2(1+\mathrm{SNR})$ frames the ultimate limit.</li>
          <li><strong>Why it is the master skill:</strong> the link budget is both the design tool and the debugging tool — when a real link underperforms, you re-derive it line by line to find the missing dB.</li>
        </ul></div>`
      }
    ],
    keyPoints: [
      String.raw`Master equation: $P_{rx} = P_{tx} + G_{tx} - L_{tx} - PL - L_{misc} + G_{rx} - L_{rx}$ (all in dB/dBm).`,
      String.raw`EIRP = $P_{tx} + G_{tx} - L_{tx}$; it is the regulated transmit figure and the transmit-side coverage driver.`,
      String.raw`Sensitivity = noise floor + SNR_req = $(-174 + 10\log_{10}B + NF) + \text{SNR}_{req}$.`,
      String.raw`Link margin $M = P_{rx} - P_{sens}$; positive closes the link, and raw margin must cover fade/rain/pointing/implementation headroom.`,
      String.raw`SNR relates to Eb/N0 via $\text{SNR} = (E_b/N_0)(R_b/B)$; higher-order modulation needs more SNR_req.`,
      String.raw`Coding gain (5-8 dB from LDPC/turbo) lowers SNR_req, improving sensitivity at the cost of overhead/latency.`,
      String.raw`Wider bandwidth or higher NF or higher modulation order all worsen (raise) sensitivity.`,
      String.raw`Fade margin for coverage p is $Q^{-1}(1-p)\sigma$; rain fade dominates above ~10 GHz for high-availability links.`,
      String.raw`Three levers to add margin: more Tx power (regulatory/battery limits), more antenna gain (narrower beam, pointing cost), more coding / lower modulation (less data rate).`,
      String.raw`Antenna gain is often the cheapest dB because it is passive and helps both EIRP and receive side.`,
      String.raw`Always separate raw margin from allocated headroom; a big-looking margin can be nearly consumed by reserves.`,
      String.raw`G/T (gain-to-noise-temperature, dB/K) is the receive-side figure of merit for satellite links.`
    ],
    diagram: [
      {
        svg: String.raw`<svg viewBox="0 0 540 300" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif"><rect x="0" y="0" width="540" height="300" fill="#1c232e"/><text x="270" y="20" fill="#e6edf3" font-size="14" text-anchor="middle">Link budget ledger (waterfall)</text><line x1="60" y1="40" x2="60" y2="260" stroke="#9aa7b5"/><line x1="60" y1="260" x2="510" y2="260" stroke="#9aa7b5"/><rect x="70" y="60" width="40" height="80" fill="#4dabf7"/><text x="90" y="55" fill="#4dabf7" font-size="10" text-anchor="middle">Ptx</text><rect x="120" y="55" width="40" height="30" fill="#63e6be"/><text x="140" y="48" fill="#63e6be" font-size="9" text-anchor="middle">+Gtx</text><rect x="170" y="55" width="40" height="130" fill="#ff6b6b"/><text x="190" y="48" fill="#ff6b6b" font-size="9" text-anchor="middle">-PL</text><rect x="220" y="185" width="40" height="20" fill="#ffa94d"/><text x="240" y="180" fill="#ffa94d" font-size="9" text-anchor="middle">-Lmisc</text><rect x="270" y="175" width="40" height="30" fill="#63e6be"/><text x="290" y="168" fill="#63e6be" font-size="9" text-anchor="middle">+Grx</text><rect x="320" y="205" width="60" height="6" fill="#e6edf3"/><text x="350" y="200" fill="#e6edf3" font-size="10" text-anchor="middle">Prx</text><line x1="60" y1="235" x2="510" y2="235" stroke="#b197fc" stroke-dasharray="4 3"/><text x="470" y="230" fill="#b197fc" font-size="10" text-anchor="end">sensitivity</text><line x1="350" y1="208" x2="350" y2="235" stroke="#63e6be" stroke-width="2"/><text x="380" y="225" fill="#63e6be" font-size="10">margin</text></svg>`,
        caption: 'Waterfall of the link budget: Tx power and gains add, losses subtract, ending at Prx; the gap above sensitivity is the link margin.'
      },
      {
        svg: String.raw`<svg viewBox="0 0 540 240" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif"><rect x="0" y="0" width="540" height="240" fill="#1c232e"/><text x="270" y="20" fill="#e6edf3" font-size="14" text-anchor="middle">Receiver sensitivity build-up</text><rect x="120" y="180" width="300" height="30" fill="#ffa94d"/><text x="270" y="200" fill="#0b0f14" font-size="11" text-anchor="middle">kTB: -174 + 10log(B) = e.g. -101 dBm</text><rect x="120" y="145" width="300" height="30" fill="#b197fc"/><text x="270" y="165" fill="#0b0f14" font-size="11" text-anchor="middle">+ NF (e.g. 6 dB) = noise floor -95 dBm</text><rect x="120" y="90" width="300" height="50" fill="#4dabf7"/><text x="270" y="120" fill="#0b0f14" font-size="11" text-anchor="middle">+ SNR_req (e.g. 15 dB)</text><line x1="80" y1="90" x2="440" y2="90" stroke="#63e6be" stroke-width="2" stroke-dasharray="5 3"/><text x="270" y="80" fill="#63e6be" font-size="12" text-anchor="middle">Sensitivity = -80 dBm</text><text x="270" y="228" fill="#9aa7b5" font-size="11" text-anchor="middle">lower is better: minimise B, NF, SNR_req</text></svg>`,
        caption: 'Sensitivity stacks up from kTB, plus noise figure (= noise floor), plus the demodulator required SNR.'
      },
      {
        svg: String.raw`<svg viewBox="0 0 540 220" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif"><rect x="0" y="0" width="540" height="220" fill="#1c232e"/><text x="270" y="20" fill="#e6edf3" font-size="14" text-anchor="middle">Allocating raw margin into headroom</text><rect x="120" y="50" width="300" height="30" fill="#63e6be"/><text x="270" y="70" fill="#0b0f14" font-size="11" text-anchor="middle">raw margin (Prx - Psens)</text><rect x="120" y="95" width="130" height="25" fill="#ff6b6b"/><text x="185" y="112" fill="#0b0f14" font-size="10" text-anchor="middle">fade margin</text><rect x="250" y="95" width="90" height="25" fill="#ffa94d"/><text x="295" y="112" fill="#0b0f14" font-size="10" text-anchor="middle">rain</text><rect x="340" y="95" width="45" height="25" fill="#b197fc"/><text x="362" y="112" fill="#0b0f14" font-size="9" text-anchor="middle">point</text><rect x="385" y="95" width="35" height="25" fill="#4dabf7"/><text x="402" y="112" fill="#0b0f14" font-size="9" text-anchor="middle">impl</text><text x="270" y="160" fill="#9aa7b5" font-size="11" text-anchor="middle">true operating margin = raw - all reserves</text><text x="270" y="185" fill="#63e6be" font-size="11" text-anchor="middle">a big raw margin can be nearly fully consumed</text></svg>`,
        caption: 'Raw margin must be partitioned into fade, rain, pointing, and implementation reserves; only the remainder is true operating margin.'
      }
    ],
    equations: [
      {
        title: 'Master link-budget equation',
        tex: String.raw`$$P_{rx} = P_{tx} + G_{tx} - L_{tx} - PL - L_{misc} + G_{rx} - L_{rx}$$`,
        derivation: String.raw`<p>Received power in linear terms is a product of gains and reciprocal losses. Taking $10\log_{10}$ turns products into sums: each gain adds, each loss subtracts. dBm for powers, dB(i) for gains/losses. The result is the received signal power at the receiver reference plane.</p>`
      },
      {
        title: 'EIRP',
        tex: String.raw`$$\text{EIRP} = P_{tx} + G_{tx} - L_{tx}$$`,
        derivation: String.raw`<p>EIRP is the transmit power an isotropic radiator would need to match the actual system's peak-direction field. It equals the PA output plus antenna gain minus feeder loss. Regulators cap EIRP because it determines the field imposed on other users.</p>`
      },
      {
        title: 'Receiver sensitivity',
        tex: String.raw`$$P_{sens} = -174 + 10\log_{10}(B) + NF + \text{SNR}_{req}$$`,
        derivation: String.raw`<p>Noise floor at the input is $kTB$ referred to 290 K (&minus;174 dBm/Hz) times bandwidth, degraded by the receiver noise figure NF. Adding the demodulator's required SNR gives the minimum signal power that meets the target BER. Everything in dB.</p>`
      },
      {
        title: 'SNR from Eb/N0',
        tex: String.raw`$$\text{SNR} = \frac{E_b}{N_0}\cdot\frac{R_b}{B}$$`,
        derivation: String.raw`<p>Signal power $S = E_b R_b$ (energy per bit times bit rate); noise power $N = N_0 B$. Their ratio $S/N = (E_b/N_0)(R_b/B)$. The factor $R_b/B$ is spectral efficiency. In dB: $\text{SNR}_{dB} = (E_b/N_0)_{dB} + 10\log_{10}(R_b/B)$.</p>`
      },
      {
        title: 'Link margin',
        tex: String.raw`$$M = P_{rx} - P_{sens}$$`,
        derivation: String.raw`<p>Difference between the received power and the minimum required. Positive margin means the link closes with headroom; the margin must exceed the sum of fade, rain, pointing, and implementation reserves for a reliable design.</p>`
      },
      {
        title: 'Fade margin for availability',
        tex: String.raw`$$M_{fade} = Q^{-1}(1-p)\cdot\sigma$$`,
        derivation: String.raw`<p>Shadowing is log-normal (Gaussian in dB, std dev $\sigma$). To achieve coverage/availability probability p, the mean received power must exceed sensitivity by $z\sigma$ where $z = Q^{-1}(1-p)$. E.g. p = 0.99 &rarr; z = 2.33.</p>`
      },
      {
        title: 'Shannon capacity limit',
        tex: String.raw`$$C = B\log_2(1 + \text{SNR})$$`,
        derivation: String.raw`<p>The theoretical maximum error-free rate over bandwidth B at a given SNR. It frames every link-budget trade: raising SNR (more power/gain/less bandwidth-noise) or bandwidth raises the achievable rate, but with diminishing logarithmic returns in SNR.</p>`
      }
    ],
    flashcards: [
      { front: String.raw`Write the master link-budget equation.`, back: String.raw`$P_{rx} = P_{tx} + G_{tx} - L_{tx} - PL - L_{misc} + G_{rx} - L_{rx}$, all in dB/dBm.` },
      { front: String.raw`Define EIRP.`, back: String.raw`Effective isotropic radiated power: $P_{tx} + G_{tx} - L_{tx}$ (dBm). The power an isotropic radiator would need to match the peak-direction field; it is what regulators cap.` },
      { front: String.raw`How is receiver sensitivity computed?`, back: String.raw`$P_{sens} = -174 + 10\log_{10}(B) + NF + \text{SNR}_{req}$ — noise floor plus the demodulator's required SNR.` },
      { front: String.raw`What is link margin?`, back: String.raw`$M = P_{rx} - P_{sens}$. Positive closes the link; it must cover fade, rain, pointing, and implementation reserves.` },
      { front: String.raw`Relate SNR to Eb/N0.`, back: String.raw`$\text{SNR} = (E_b/N_0)(R_b/B)$; the factor $R_b/B$ is spectral efficiency (bits/s/Hz).` },
      { front: String.raw`How does coding gain help the budget?`, back: String.raw`It lowers the required Eb/N0 (and hence SNR_req), improving sensitivity by 5-8 dB for strong codes, at the cost of overhead and latency.` },
      { front: String.raw`What worsens receiver sensitivity?`, back: String.raw`Wider bandwidth (more noise), higher noise figure, and higher-order modulation (more SNR_req). All raise the required signal power.` },
      { front: String.raw`Fade margin formula and example.`, back: String.raw`$M_{fade}=Q^{-1}(1-p)\sigma$. For 99% availability (z=2.33) at sigma=6 dB, about 14 dB.` },
      { front: String.raw`Which band makes rain fade a dominant budget term?`, back: String.raw`Above roughly 10 GHz (Ku/Ka band); rain attenuation can be tens of dB for high-availability links.` },
      { front: String.raw`Three levers to add link margin?`, back: String.raw`Increase Tx power (regulatory/battery limited), increase antenna gain (narrower beam, pointing cost), or add coding / lower modulation order (less data rate).` },
      { front: String.raw`Why is antenna gain often the cheapest dB?`, back: String.raw`It is passive (no extra power/regulatory issue) and helps both EIRP (transmit) and the receive side, though it narrows beamwidth.` },
      { front: String.raw`What is G/T?`, back: String.raw`Gain-to-noise-temperature ratio (dB/K) — the receive-side figure of merit combining antenna gain and system noise temperature, used for satellite earth stations.` },
      { front: String.raw`State the Shannon capacity relation for a link.`, back: String.raw`$C = B\log_2(1+\text{SNR})$ — the maximum error-free rate, framing all budget trades.` },
      { front: String.raw`Why separate raw margin from headroom?`, back: String.raw`A large raw margin can be almost entirely consumed by fade/rain/pointing/implementation reserves; only the remainder is true operating margin.` }
    ],
    mcqs: [
      { q: String.raw`EIRP is defined as:`, options: [String.raw`$P_{tx} + G_{tx} - L_{tx}$`, String.raw`$P_{tx} + G_{rx}$`, String.raw`$P_{rx} - PL$`, String.raw`$G_{tx} + G_{rx}$`], answer: 0, explain: String.raw`EIRP folds transmit power, transmit antenna gain, and feeder loss into one figure.` },
      { q: String.raw`A receiver has B = 10 MHz, NF = 5 dB, and needs SNR_req = 12 dB. Its sensitivity is:`, options: [String.raw`&minus;104 dBm`, String.raw`&minus;87 dBm`, String.raw`&minus;110 dBm`, String.raw`&minus;92 dBm`], answer: 1, explain: String.raw`$10\log_{10}(10\times10^6)=70$ dB, so noise floor $= -174 + 70 + 5 = -99$ dBm; sensitivity $= -99 + 12 = -87$ dBm.` },
      { q: String.raw`If $P_{rx} = -75$ dBm and sensitivity is &minus;90 dBm, the link margin is:`, options: [String.raw`+15 dB`, String.raw`&minus;15 dB`, String.raw`+165 dB`, String.raw`0 dB`], answer: 0, explain: String.raw`$M = P_{rx}-P_{sens} = -75 - (-90) = +15$ dB.` },
      { q: String.raw`Doubling receiver bandwidth changes sensitivity by:`, options: [String.raw`&minus;3 dB (better)`, String.raw`+3 dB (worse)`, String.raw`+6 dB`, String.raw`no change`], answer: 1, explain: String.raw`Noise power rises 3 dB, so the required signal (sensitivity) rises 3 dB — worse.` },
      { q: String.raw`Adding 6 dB of coding gain to a link primarily:`, options: [String.raw`Raises EIRP by 6 dB`, String.raw`Lowers SNR_req by 6 dB, improving sensitivity`, String.raw`Increases path loss`, String.raw`Doubles bandwidth`], answer: 1, explain: String.raw`Coding reduces the required Eb/N0 / SNR_req, so sensitivity improves by the coding gain.` },
      { q: String.raw`Which term is most likely to dominate the loss budget of a terrestrial link?`, options: [String.raw`Connector loss`, String.raw`Path loss`, String.raw`Polarisation mismatch`, String.raw`Receiver NF`], answer: 1, explain: String.raw`Path loss is typically 80-140 dB, far larger than any other single term.` },
      { q: String.raw`For 99% availability with sigma = 6 dB (Q^-1(0.01)=2.33), fade margin is about:`, options: [String.raw`6 dB`, String.raw`14 dB`, String.raw`3 dB`, String.raw`23 dB`], answer: 1, explain: String.raw`$2.33\times6 = 14.0$ dB.` },
      { q: String.raw`Higher-order modulation (e.g. 256-QAM vs QPSK) affects the budget by:`, options: [String.raw`Lowering SNR_req`, String.raw`Raising SNR_req (needing more margin)`, String.raw`Lowering path loss`, String.raw`Raising EIRP`], answer: 1, explain: String.raw`Denser constellations need a higher SNR for the same BER, raising SNR_req and thus sensitivity.` },
      { q: String.raw`G/T is a figure of merit for:`, options: [String.raw`The transmit chain`, String.raw`The receive chain (antenna gain over noise temperature)`, String.raw`Path loss`, String.raw`Cable loss`], answer: 1, explain: String.raw`G/T (dB/K) combines receive antenna gain and system noise temperature — a receive-side quality metric.` },
      { q: String.raw`Which lever adds margin without spending transmit power or reducing data rate?`, options: [String.raw`Increase Tx power`, String.raw`Increase antenna gain`, String.raw`Lower modulation order`, String.raw`Add FEC overhead`], answer: 1, explain: String.raw`Antenna gain is passive and improves both EIRP and receive sensitivity, with no power or rate penalty (but narrower beam).` },
      { q: String.raw`SNR expressed from Eb/N0 is:`, options: [String.raw`$(E_b/N_0)(B/R_b)$`, String.raw`$(E_b/N_0)(R_b/B)$`, String.raw`$(E_b/N_0) + B$`, String.raw`$(N_0/E_b)(R_b/B)$`], answer: 1, explain: String.raw`$S/N = E_b R_b / (N_0 B) = (E_b/N_0)(R_b/B)$.` },
      { q: String.raw`A link shows +25 dB raw margin but must reserve 12 (fade) + 8 (rain) + 3 (pointing). True operating margin is:`, options: [String.raw`+25 dB`, String.raw`+2 dB`, String.raw`&minus;23 dB`, String.raw`+48 dB`], answer: 1, explain: String.raw`$25 - (12+8+3) = 25 - 23 = +2$ dB — barely closing.` }
    ],
    numericals: [
      { q: String.raw`Tx power +30 dBm, Tx feeder loss 2 dB, Tx antenna 18 dBi, path loss 130 dB, misc loss 4 dB, Rx antenna 18 dBi, Rx feeder 2 dB. Find EIRP and Prx.`, solution: String.raw`<p><b>Formula.</b> $$\mathrm{EIRP}=P_{tx}+G_{tx}-L_{tx},\qquad P_{rx}=\mathrm{EIRP}-PL-L_{misc}+G_{rx}-L_{rx}.$$</p><p><b>Substitute.</b> $\mathrm{EIRP}=30-2+18$; $P_{rx}=\mathrm{EIRP}-130-4+18-2$.</p><p><b>Compute.</b> $\mathrm{EIRP}=+46$ dBm; $P_{rx}=46-130-4+18-2=-72$ dBm.</p><p><b>Explanation.</b> Bundling the transmit side into a +46 dBm EIRP simplifies the ledger; path loss then dominates, landing $P_{rx}$ at −72 dBm. Whether the link closes depends on comparing this to sensitivity.</p>` },
      { q: String.raw`A receiver: B = 5 MHz, NF = 3 dB, target BER needs Eb/N0 = 9 dB, spectral efficiency R_b/B = 2 (i.e. +3 dB). Find SNR_req and sensitivity.`, solution: String.raw`<p><b>Formula.</b> $$\mathrm{SNR}_{req}=\frac{E_b}{N_0}+10\log_{10}\frac{R_b}{B},\qquad P_{sens}=-174+10\log_{10}B+NF+\mathrm{SNR}_{req}.$$</p><p><b>Substitute.</b> $\mathrm{SNR}_{req}=9+10\log_{10}(2)$; $P_{sens}=-174+10\log_{10}(5\times10^{6})+3+\mathrm{SNR}_{req}$.</p><p><b>Compute.</b> $\mathrm{SNR}_{req}=9+3.01=12.0$ dB. Noise floor $=-174+67.0+3=-104$ dBm. $P_{sens}=-104+12=-92$ dBm.</p><p><b>Explanation.</b> The spectral-efficiency factor adds 3 dB to the raw $E_b/N_0$ because each Hz carries 2 bits/s, and the receiver decodes down to −92 dBm. Higher spectral efficiency always costs SNR, hence sensitivity.</p>` },
      { q: String.raw`Using Prx = &minus;72 dBm from the first numerical and sensitivity &minus;92 dBm, compute the margin. If 12 dB fade and 4 dB rain reserves are needed, what is the true operating margin?`, solution: String.raw`<p><b>Formula.</b> $$M=P_{rx}-P_{sens},\qquad M_{true}=M-M_{fade}-M_{rain}.$$</p><p><b>Substitute.</b> $M=-72-(-92)$; $M_{true}=M-12-4$.</p><p><b>Compute.</b> $M=+20$ dB; $M_{true}=20-12-4=+4$ dB.</p><p><b>Explanation.</b> A healthy-looking 20 dB raw margin shrinks to just 4 dB of true operating slack once fade and rain reserves are allocated. This is why raw margin must always be separated from headroom — add antenna gain or lower the MCS to build robustness.</p>` },
      { q: String.raw`A satellite downlink: EIRP 50 dBW, FSPL 205 dB, Rx antenna 40 dBi, misc 3 dB. System noise temperature 150 K, bandwidth 36 MHz. Find received power (dBW) and the input C/N (use N = kTB).`, solution: String.raw`<p><b>Formula.</b> $$P_{rx}=\mathrm{EIRP}-\mathrm{FSPL}+G_{rx}-L_{misc},\qquad N=kTB,\qquad C/N=P_{rx}-N.$$</p><p><b>Substitute.</b> $P_{rx}=50-205+40-3$; $N=1.38\times10^{-23}\times150\times36\times10^{6}$.</p><p><b>Compute.</b> $P_{rx}=-118$ dBW. $N=7.45\times10^{-14}$ W $=10\log_{10}(7.45\times10^{-14})=-131.3$ dBW. $C/N=-118-(-131.3)=+13.3$ dB.</p><p><b>Explanation.</b> Despite a −118 dBW signal after 205 dB of path loss, the cold 150 K system and 36 MHz noise bandwidth keep noise at −131 dBW, leaving a workable +13.3 dB C/N. Satellite links live on low noise temperature (high G/T), not high received power.</p>` },
      { q: String.raw`A Wi-Fi radio is limited to +36 dBm EIRP by regulation. Its antenna is 20 dBi and feeder loss 1 dB. What is the maximum allowed PA output power?`, solution: String.raw`<p><b>Formula.</b> Invert the EIRP definition for transmit power: $$P_{tx}=\mathrm{EIRP}-G_{tx}+L_{tx}.$$</p><p><b>Substitute.</b> $P_{tx}=36-20+1$.</p><p><b>Compute.</b> $P_{tx}=+17$ dBm.</p><p><b>Explanation.</b> A high-gain 20 dBi antenna forces the PA down to +17 dBm to stay under the +36 dBm EIRP cap. Regulators limit EIRP, not PA power, so antenna gain and transmit power trade directly against each other.</p>` },
      { q: String.raw`A link is 5 dB short. Compare adding 5 dB via Tx power vs antenna gain vs coding. Which improves the receive-side too, and which is regulatory-limited?`, solution: String.raw`<p><b>Formula.</b> The margin $M=P_{rx}-P_{sens}$ can be raised through any term: $P_{rx}$ via $\mathrm{EIRP}=P_{tx}+G_{tx}-L_{tx}$ (Tx power or gain) or via $G_{rx}$; $P_{sens}=-174+10\log_{10}B+NF+\mathrm{SNR}_{req}$ via coding gain that lowers $\mathrm{SNR}_{req}$.</p><p><b>Substitute.</b> Each lever must supply $\Delta M=+5$ dB: $\Delta P_{tx}=+5$, or $\Delta G=+5$, or $\Delta\mathrm{SNR}_{req}=-5$.</p><p><b>Compute.</b> Tx power +5 dB: raises EIRP 5 dB but may exceed an EIRP cap; costs battery/PA; receive side unchanged. Antenna gain +5 dB: raises EIRP and, on the Rx antenna, sensitivity too; passive, but narrows the beam and complicates pointing. Coding +5 dB: lowers $\mathrm{SNR}_{req}$ 5 dB, improving sensitivity at the cost of overhead/latency.</p><p><b>Explanation.</b> Antenna gain is the best value — regulatory-neutral on receive and helping both directions — while Tx power is the regulatory-limited lever and coding trades throughput. All three buy the same 5 dB but with different costs.</p>` },
      { q: String.raw`Compute sensitivity for LTE: B = 9 MHz effective, NF = 7 dB, SNR_req = &minus;1 dB (heavily coded QPSK). Comment on how negative SNR_req is possible.`, solution: String.raw`<p><b>Formula.</b> $$P_{sens}=-174+10\log_{10}B+NF+\mathrm{SNR}_{req},$$ where $\mathrm{SNR}_{req}$ may be negative when coding and processing gain let the channel run below the noise floor.</p><p><b>Substitute.</b> $P_{sens}=-174+10\log_{10}(9\times10^{6})+7+(-1)$.</p><p><b>Compute.</b> $10\log_{10}(9\times10^{6})=69.5$ dB. Noise floor $=-174+69.5+7=-97.5$ dBm. $P_{sens}=-97.5-1=-98.5$ dBm.</p><p><b>Explanation.</b> A −1 dB required SNR means the wideband signal can sit just below the noise floor and still decode, because strong FEC keeps the per-bit $E_b/N_0$ positive even when channel SNR is negative. That is what lets heavily coded LTE reach −98.5 dBm.</p>` }
    ],
    realWorld: String.raw`<p>Link budgets are the first document produced for any new radio system: cellular base-station coverage, Wi-Fi APs, satellite (GEO/LEO) uplink and downlink, deep-space (NASA's DSN closes links from Voyager at &minus;160 dBm-class signals using huge dishes and heavy coding), IoT (LoRaWAN advertises a ~157 dB link budget as its headline range spec), and radar. Regulators enforce EIRP limits that force the power-vs-gain trade. Satellite operators trade rain-fade margin against availability targets and Ka-band capacity. The link budget is also the debugging tool: when a deployed link underperforms, engineers re-derive the budget line by line to find the missing dB — usually an unaccounted connector, a mispointed dish, an optimistic path-loss model, or a noise-figure regression. Mastery of link budgets is what separates an RF engineer who can specify and troubleshoot systems from one who can only read datasheets.</p>`,
    related: ['path-loss', 'rssi', 'noise-figure', 'noise-floor', 'antenna-gain', 'fec']
  }
);
